	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_unknown_1::
	.incbin "sound/direct_sound_samples/unknown_01.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_unknown_2::
	.incbin "sound/direct_sound_samples/unknown_02.bin"

	.align 2
DirectSoundWaveData_unknown_3::
	.incbin "sound/direct_sound_samples/unknown_03.bin"

	.align 2
DirectSoundWaveData_unknown_4::
	.incbin "sound/direct_sound_samples/unknown_04.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_unknown_5::
	.incbin "sound/direct_sound_samples/unknown_05.bin"

	.align 2
DirectSoundWaveData_unknown_6::
	.incbin "sound/direct_sound_samples/unknown_06.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_unknown_7::
	.incbin "sound/direct_sound_samples/unknown_07.bin"

	.align 2
DirectSoundWaveData_unknown_8::
	.incbin "sound/direct_sound_samples/unknown_08.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_unknown_9::
	.incbin "sound/direct_sound_samples/unknown_09.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_unknown_10::
	.incbin "sound/direct_sound_samples/unknown_10.bin"

	.align 2
DirectSoundWaveData_unknown_11::
	.incbin "sound/direct_sound_samples/unknown_11.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_unknown_12::
	.incbin "sound/direct_sound_samples/unknown_12.bin"

	.align 2
DirectSoundWaveData_unknown_13::
	.incbin "sound/direct_sound_samples/unknown_13.bin"

	.align 2
DirectSoundWaveData_unknown_14::
	.incbin "sound/direct_sound_samples/unknown_14.bin"

	.align 2
DirectSoundWaveData_unknown_15::
	.incbin "sound/direct_sound_samples/unknown_15.bin"

	.align 2
DirectSoundWaveData_unknown_16::
	.incbin "sound/direct_sound_samples/unknown_16.bin"

	.align 2
DirectSoundWaveData_unknown_17::
	.incbin "sound/direct_sound_samples/unknown_17.bin"

	.align 2
Cry_Bulbasaur::
	.incbin "sound/direct_sound_samples/cries/bulbasaur.bin"

	.align 2
Cry_Ivysaur::
	.incbin "sound/direct_sound_samples/cries/ivysaur.bin"

	.align 2
Cry_Venusaur::
	.incbin "sound/direct_sound_samples/cries/venusaur.bin"

	.align 2
Cry_Charmander::
	.incbin "sound/direct_sound_samples/cries/charmander.bin"

	.align 2
Cry_Charmeleon::
	.incbin "sound/direct_sound_samples/cries/charmeleon.bin"

	.align 2
Cry_Charizard::
	.incbin "sound/direct_sound_samples/cries/charizard.bin"

	.align 2
Cry_Squirtle::
	.incbin "sound/direct_sound_samples/cries/squirtle.bin"

	.align 2
Cry_Wartortle::
	.incbin "sound/direct_sound_samples/cries/wartortle.bin"

	.align 2
Cry_Blastoise::
	.incbin "sound/direct_sound_samples/cries/blastoise.bin"

	.align 2
Cry_Caterpie::
	.incbin "sound/direct_sound_samples/cries/caterpie.bin"

	.align 2
Cry_Metapod::
	.incbin "sound/direct_sound_samples/cries/metapod.bin"

	.align 2
Cry_Butterfree::
	.incbin "sound/direct_sound_samples/cries/butterfree.bin"

	.align 2
Cry_Weedle::
	.incbin "sound/direct_sound_samples/cries/weedle.bin"

	.align 2
Cry_Kakuna::
	.incbin "sound/direct_sound_samples/cries/kakuna.bin"

	.align 2
Cry_Beedrill::
	.incbin "sound/direct_sound_samples/cries/beedrill.bin"

	.align 2
Cry_Pidgey::
	.incbin "sound/direct_sound_samples/cries/pidgey.bin"

	.align 2
Cry_Pidgeotto::
	.incbin "sound/direct_sound_samples/cries/pidgeotto.bin"

	.align 2
Cry_Pidgeot::
	.incbin "sound/direct_sound_samples/cries/pidgeot.bin"

	.align 2
Cry_Rattata::
	.incbin "sound/direct_sound_samples/cries/rattata.bin"

	.align 2
Cry_Raticate::
	.incbin "sound/direct_sound_samples/cries/raticate.bin"

	.align 2
Cry_Spearow::
	.incbin "sound/direct_sound_samples/cries/spearow.bin"

	.align 2
Cry_Fearow::
	.incbin "sound/direct_sound_samples/cries/fearow.bin"

	.align 2
Cry_Ekans::
	.incbin "sound/direct_sound_samples/cries/ekans.bin"

	.align 2
Cry_Arbok::
	.incbin "sound/direct_sound_samples/cries/arbok.bin"

	.align 2
Cry_Pikachu::
	.incbin "sound/direct_sound_samples/cries/pikachu.bin"

	.align 2
Cry_Raichu::
	.incbin "sound/direct_sound_samples/cries/raichu.bin"

	.align 2
Cry_Sandshrew::
	.incbin "sound/direct_sound_samples/cries/sandshrew.bin"

	.align 2
Cry_Sandslash::
	.incbin "sound/direct_sound_samples/cries/sandslash.bin"

	.align 2
Cry_NidoranF::
	.incbin "sound/direct_sound_samples/cries/nidoran_f.bin"

	.align 2
Cry_Nidorina::
	.incbin "sound/direct_sound_samples/cries/nidorina.bin"

	.align 2
Cry_Nidoqueen::
	.incbin "sound/direct_sound_samples/cries/nidoqueen.bin"

	.align 2
Cry_NidoranM::
	.incbin "sound/direct_sound_samples/cries/nidoran_m.bin"

	.align 2
Cry_Nidorino::
	.incbin "sound/direct_sound_samples/cries/nidorino.bin"

	.align 2
Cry_Nidoking::
	.incbin "sound/direct_sound_samples/cries/nidoking.bin"

	.align 2
Cry_Clefairy::
	.incbin "sound/direct_sound_samples/cries/clefairy.bin"

	.align 2
Cry_Clefable::
	.incbin "sound/direct_sound_samples/cries/clefable.bin"

	.align 2
Cry_Vulpix::
	.incbin "sound/direct_sound_samples/cries/vulpix.bin"

	.align 2
Cry_Ninetales::
	.incbin "sound/direct_sound_samples/cries/ninetales.bin"

	.align 2
Cry_Jigglypuff::
	.incbin "sound/direct_sound_samples/cries/jigglypuff.bin"

	.align 2
Cry_Wigglytuff::
	.incbin "sound/direct_sound_samples/cries/wigglytuff.bin"

	.align 2
Cry_Zubat::
	.incbin "sound/direct_sound_samples/cries/zubat.bin"

	.align 2
Cry_Golbat::
	.incbin "sound/direct_sound_samples/cries/golbat.bin"

	.align 2
Cry_Oddish::
	.incbin "sound/direct_sound_samples/cries/oddish.bin"

	.align 2
Cry_Gloom::
	.incbin "sound/direct_sound_samples/cries/gloom.bin"

	.align 2
Cry_Vileplume::
	.incbin "sound/direct_sound_samples/cries/vileplume.bin"

	.align 2
Cry_Paras::
	.incbin "sound/direct_sound_samples/cries/paras.bin"

	.align 2
Cry_Parasect::
	.incbin "sound/direct_sound_samples/cries/parasect.bin"

	.align 2
Cry_Venonat::
	.incbin "sound/direct_sound_samples/cries/venonat.bin"

	.align 2
Cry_Venomoth::
	.incbin "sound/direct_sound_samples/cries/venomoth.bin"

	.align 2
Cry_Diglett::
	.incbin "sound/direct_sound_samples/cries/diglett.bin"

	.align 2
Cry_Dugtrio::
	.incbin "sound/direct_sound_samples/cries/dugtrio.bin"

	.align 2
Cry_Meowth::
	.incbin "sound/direct_sound_samples/cries/meowth.bin"

	.align 2
Cry_Persian::
	.incbin "sound/direct_sound_samples/cries/persian.bin"

	.align 2
Cry_Psyduck::
	.incbin "sound/direct_sound_samples/cries/psyduck.bin"

	.align 2
Cry_Golduck::
	.incbin "sound/direct_sound_samples/cries/golduck.bin"

	.align 2
Cry_Mankey::
	.incbin "sound/direct_sound_samples/cries/mankey.bin"

	.align 2
Cry_Primeape::
	.incbin "sound/direct_sound_samples/cries/primeape.bin"

	.align 2
Cry_Growlithe::
	.incbin "sound/direct_sound_samples/cries/growlithe.bin"

	.align 2
Cry_Arcanine::
	.incbin "sound/direct_sound_samples/cries/arcanine.bin"

	.align 2
Cry_Poliwag::
	.incbin "sound/direct_sound_samples/cries/poliwag.bin"

	.align 2
Cry_Poliwhirl::
	.incbin "sound/direct_sound_samples/cries/poliwhirl.bin"

	.align 2
Cry_Poliwrath::
	.incbin "sound/direct_sound_samples/cries/poliwrath.bin"

	.align 2
Cry_Abra::
	.incbin "sound/direct_sound_samples/cries/abra.bin"

	.align 2
Cry_Kadabra::
	.incbin "sound/direct_sound_samples/cries/kadabra.bin"

	.align 2
Cry_Alakazam::
	.incbin "sound/direct_sound_samples/cries/alakazam.bin"

	.align 2
Cry_Machop::
	.incbin "sound/direct_sound_samples/cries/machop.bin"

	.align 2
Cry_Machoke::
	.incbin "sound/direct_sound_samples/cries/machoke.bin"

	.align 2
Cry_Machamp::
	.incbin "sound/direct_sound_samples/cries/machamp.bin"

	.align 2
Cry_Bellsprout::
	.incbin "sound/direct_sound_samples/cries/bellsprout.bin"

	.align 2
Cry_Weepinbell::
	.incbin "sound/direct_sound_samples/cries/weepinbell.bin"

	.align 2
Cry_Victreebel::
	.incbin "sound/direct_sound_samples/cries/victreebel.bin"

	.align 2
Cry_Tentacool::
	.incbin "sound/direct_sound_samples/cries/tentacool.bin"

	.align 2
Cry_Tentacruel::
	.incbin "sound/direct_sound_samples/cries/tentacruel.bin"

	.align 2
Cry_Geodude::
	.incbin "sound/direct_sound_samples/cries/geodude.bin"

	.align 2
Cry_Graveler::
	.incbin "sound/direct_sound_samples/cries/graveler.bin"

	.align 2
Cry_Golem::
	.incbin "sound/direct_sound_samples/cries/golem.bin"

	.align 2
Cry_Ponyta::
	.incbin "sound/direct_sound_samples/cries/ponyta.bin"

	.align 2
Cry_Rapidash::
	.incbin "sound/direct_sound_samples/cries/rapidash.bin"

	.align 2
Cry_Slowpoke::
	.incbin "sound/direct_sound_samples/cries/slowpoke.bin"

	.align 2
Cry_Slowbro::
	.incbin "sound/direct_sound_samples/cries/slowbro.bin"

	.align 2
Cry_Magnemite::
	.incbin "sound/direct_sound_samples/cries/magnemite.bin"

	.align 2
Cry_Magneton::
	.incbin "sound/direct_sound_samples/cries/magneton.bin"

	.align 2
Cry_Farfetchd::
	.incbin "sound/direct_sound_samples/cries/farfetchd.bin"

	.align 2
Cry_Doduo::
	.incbin "sound/direct_sound_samples/cries/doduo.bin"

	.align 2
Cry_Dodrio::
	.incbin "sound/direct_sound_samples/cries/dodrio.bin"

	.align 2
Cry_Seel::
	.incbin "sound/direct_sound_samples/cries/seel.bin"

	.align 2
Cry_Dewgong::
	.incbin "sound/direct_sound_samples/cries/dewgong.bin"

	.align 2
Cry_Grimer::
	.incbin "sound/direct_sound_samples/cries/grimer.bin"

	.align 2
Cry_Muk::
	.incbin "sound/direct_sound_samples/cries/muk.bin"

	.align 2
Cry_Shellder::
	.incbin "sound/direct_sound_samples/cries/shellder.bin"

	.align 2
Cry_Cloyster::
	.incbin "sound/direct_sound_samples/cries/cloyster.bin"

	.align 2
Cry_Gastly::
	.incbin "sound/direct_sound_samples/cries/gastly.bin"

	.align 2
Cry_Haunter::
	.incbin "sound/direct_sound_samples/cries/haunter.bin"

	.align 2
Cry_Gengar::
	.incbin "sound/direct_sound_samples/cries/gengar.bin"

	.align 2
Cry_Onix::
	.incbin "sound/direct_sound_samples/cries/onix.bin"

	.align 2
Cry_Drowzee::
	.incbin "sound/direct_sound_samples/cries/drowzee.bin"

	.align 2
Cry_Hypno::
	.incbin "sound/direct_sound_samples/cries/hypno.bin"

	.align 2
Cry_Krabby::
	.incbin "sound/direct_sound_samples/cries/krabby.bin"

	.align 2
Cry_Kingler::
	.incbin "sound/direct_sound_samples/cries/kingler.bin"

	.align 2
Cry_Voltorb::
	.incbin "sound/direct_sound_samples/cries/voltorb.bin"

	.align 2
Cry_Electrode::
	.incbin "sound/direct_sound_samples/cries/electrode.bin"

	.align 2
Cry_Exeggcute::
	.incbin "sound/direct_sound_samples/cries/exeggcute.bin"

	.align 2
Cry_Exeggutor::
	.incbin "sound/direct_sound_samples/cries/exeggutor.bin"

	.align 2
Cry_Cubone::
	.incbin "sound/direct_sound_samples/cries/cubone.bin"

	.align 2
Cry_Marowak::
	.incbin "sound/direct_sound_samples/cries/marowak.bin"

	.align 2
Cry_Hitmonlee::
	.incbin "sound/direct_sound_samples/cries/hitmonlee.bin"

	.align 2
Cry_Hitmonchan::
	.incbin "sound/direct_sound_samples/cries/hitmonchan.bin"

	.align 2
Cry_Lickitung::
	.incbin "sound/direct_sound_samples/cries/lickitung.bin"

	.align 2
Cry_Koffing::
	.incbin "sound/direct_sound_samples/cries/koffing.bin"

	.align 2
Cry_Weezing::
	.incbin "sound/direct_sound_samples/cries/weezing.bin"

	.align 2
Cry_Rhyhorn::
	.incbin "sound/direct_sound_samples/cries/rhyhorn.bin"

	.align 2
Cry_Rhydon::
	.incbin "sound/direct_sound_samples/cries/rhydon.bin"

	.align 2
Cry_Chansey::
	.incbin "sound/direct_sound_samples/cries/chansey.bin"

	.align 2
Cry_Tangela::
	.incbin "sound/direct_sound_samples/cries/tangela.bin"

	.align 2
Cry_Kangaskhan::
	.incbin "sound/direct_sound_samples/cries/kangaskhan.bin"

	.align 2
Cry_Horsea::
	.incbin "sound/direct_sound_samples/cries/horsea.bin"

	.align 2
Cry_Seadra::
	.incbin "sound/direct_sound_samples/cries/seadra.bin"

	.align 2
Cry_Goldeen::
	.incbin "sound/direct_sound_samples/cries/goldeen.bin"

	.align 2
Cry_Seaking::
	.incbin "sound/direct_sound_samples/cries/seaking.bin"

	.align 2
Cry_Staryu::
	.incbin "sound/direct_sound_samples/cries/staryu.bin"

	.align 2
Cry_Starmie::
	.incbin "sound/direct_sound_samples/cries/starmie.bin"

	.align 2
Cry_MrMime::
	.incbin "sound/direct_sound_samples/cries/mr_mime.bin"

	.align 2
Cry_Scyther::
	.incbin "sound/direct_sound_samples/cries/scyther.bin"

	.align 2
Cry_Jynx::
	.incbin "sound/direct_sound_samples/cries/jynx.bin"

	.align 2
Cry_Electabuzz::
	.incbin "sound/direct_sound_samples/cries/electabuzz.bin"

	.align 2
Cry_Magmar::
	.incbin "sound/direct_sound_samples/cries/magmar.bin"

	.align 2
Cry_Pinsir::
	.incbin "sound/direct_sound_samples/cries/pinsir.bin"

	.align 2
Cry_Tauros::
	.incbin "sound/direct_sound_samples/cries/tauros.bin"

	.align 2
Cry_Magikarp::
	.incbin "sound/direct_sound_samples/cries/magikarp.bin"

	.align 2
Cry_Gyarados::
	.incbin "sound/direct_sound_samples/cries/gyarados.bin"

	.align 2
Cry_Lapras::
	.incbin "sound/direct_sound_samples/cries/lapras.bin"

	.align 2
Cry_Ditto::
	.incbin "sound/direct_sound_samples/cries/ditto.bin"

	.align 2
Cry_Eevee::
	.incbin "sound/direct_sound_samples/cries/eevee.bin"

	.align 2
Cry_Vaporeon::
	.incbin "sound/direct_sound_samples/cries/vaporeon.bin"

	.align 2
Cry_Jolteon::
	.incbin "sound/direct_sound_samples/cries/jolteon.bin"

	.align 2
Cry_Flareon::
	.incbin "sound/direct_sound_samples/cries/flareon.bin"

	.align 2
Cry_Porygon::
	.incbin "sound/direct_sound_samples/cries/porygon.bin"

	.align 2
Cry_Omanyte::
	.incbin "sound/direct_sound_samples/cries/omanyte.bin"

	.align 2
Cry_Omastar::
	.incbin "sound/direct_sound_samples/cries/omastar.bin"

	.align 2
Cry_Kabuto::
	.incbin "sound/direct_sound_samples/cries/kabuto.bin"

	.align 2
Cry_Kabutops::
	.incbin "sound/direct_sound_samples/cries/kabutops.bin"

	.align 2
Cry_Aerodactyl::
	.incbin "sound/direct_sound_samples/cries/aerodactyl.bin"

	.align 2
Cry_Snorlax::
	.incbin "sound/direct_sound_samples/cries/snorlax.bin"

	.align 2
Cry_Articuno::
	.incbin "sound/direct_sound_samples/cries/articuno.bin"

	.align 2
Cry_Zapdos::
	.incbin "sound/direct_sound_samples/cries/zapdos.bin"

	.align 2
Cry_Moltres::
	.incbin "sound/direct_sound_samples/cries/moltres.bin"

	.align 2
Cry_Dratini::
	.incbin "sound/direct_sound_samples/cries/dratini.bin"

	.align 2
Cry_Dragonair::
	.incbin "sound/direct_sound_samples/cries/dragonair.bin"

	.align 2
Cry_Dragonite::
	.incbin "sound/direct_sound_samples/cries/dragonite.bin"

	.align 2
Cry_Mewtwo::
	.incbin "sound/direct_sound_samples/cries/mewtwo.bin"

	.align 2
Cry_Mew::
	.incbin "sound/direct_sound_samples/cries/mew.bin"

	.align 2
Cry_Chikorita::
	.incbin "sound/direct_sound_samples/cries/chikorita.bin"

	.align 2
Cry_Bayleef::
	.incbin "sound/direct_sound_samples/cries/bayleef.bin"

	.align 2
Cry_Meganium::
	.incbin "sound/direct_sound_samples/cries/meganium.bin"

	.align 2
Cry_Cyndaquil::
	.incbin "sound/direct_sound_samples/cries/cyndaquil.bin"

	.align 2
Cry_Quilava::
	.incbin "sound/direct_sound_samples/cries/quilava.bin"

	.align 2
Cry_Typhlosion::
	.incbin "sound/direct_sound_samples/cries/typhlosion.bin"

	.align 2
Cry_Totodile::
	.incbin "sound/direct_sound_samples/cries/totodile.bin"

	.align 2
Cry_Croconaw::
	.incbin "sound/direct_sound_samples/cries/croconaw.bin"

	.align 2
Cry_Feraligatr::
	.incbin "sound/direct_sound_samples/cries/feraligatr.bin"

	.align 2
Cry_Sentret::
	.incbin "sound/direct_sound_samples/cries/sentret.bin"

	.align 2
Cry_Furret::
	.incbin "sound/direct_sound_samples/cries/furret.bin"

	.align 2
Cry_Hoothoot::
	.incbin "sound/direct_sound_samples/cries/hoothoot.bin"

	.align 2
Cry_Noctowl::
	.incbin "sound/direct_sound_samples/cries/noctowl.bin"

	.align 2
Cry_Ledyba::
	.incbin "sound/direct_sound_samples/cries/ledyba.bin"

	.align 2
Cry_Ledian::
	.incbin "sound/direct_sound_samples/cries/ledian.bin"

	.align 2
Cry_Spinarak::
	.incbin "sound/direct_sound_samples/cries/spinarak.bin"

	.align 2
Cry_Ariados::
	.incbin "sound/direct_sound_samples/cries/ariados.bin"

	.align 2
Cry_Crobat::
	.incbin "sound/direct_sound_samples/cries/crobat.bin"

	.align 2
Cry_Chinchou::
	.incbin "sound/direct_sound_samples/cries/chinchou.bin"

	.align 2
Cry_Lanturn::
	.incbin "sound/direct_sound_samples/cries/lanturn.bin"

	.align 2
Cry_Pichu::
	.incbin "sound/direct_sound_samples/cries/pichu.bin"

	.align 2
Cry_Cleffa::
	.incbin "sound/direct_sound_samples/cries/cleffa.bin"

	.align 2
Cry_Igglybuff::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Togepi::
	.incbin "sound/direct_sound_samples/cries/togepi.bin"

	.align 2
Cry_Togetic::
	.incbin "sound/direct_sound_samples/cries/togetic.bin"

	.align 2
Cry_Natu::
	.incbin "sound/direct_sound_samples/cries/natu.bin"

	.align 2
Cry_Xatu::
	.incbin "sound/direct_sound_samples/cries/xatu.bin"

	.align 2
Cry_Mareep::
	.incbin "sound/direct_sound_samples/cries/mareep.bin"

	.align 2
Cry_Flaaffy::
	.incbin "sound/direct_sound_samples/cries/flaaffy.bin"

	.align 2
Cry_Ampharos::
	.incbin "sound/direct_sound_samples/cries/ampharos.bin"

	.align 2
Cry_Bellossom::
	.incbin "sound/direct_sound_samples/cries/bellossom.bin"

	.align 2
Cry_Marill::
	.incbin "sound/direct_sound_samples/cries/marill.bin"

	.align 2
Cry_Azumarill::
	.incbin "sound/direct_sound_samples/cries/azumarill.bin"

	.align 2
Cry_Sudowoodo::
	.incbin "sound/direct_sound_samples/cries/sudowoodo.bin"

	.align 2
Cry_Politoed::
	.incbin "sound/direct_sound_samples/cries/politoed.bin"

	.align 2
Cry_Hoppip::
	.incbin "sound/direct_sound_samples/cries/hoppip.bin"

	.align 2
Cry_Skiploom::
	.incbin "sound/direct_sound_samples/cries/skiploom.bin"

	.align 2
Cry_Jumpluff::
	.incbin "sound/direct_sound_samples/cries/jumpluff.bin"

	.align 2
Cry_Aipom::
	.incbin "sound/direct_sound_samples/cries/aipom.bin"

	.align 2
Cry_Sunkern::
	.incbin "sound/direct_sound_samples/cries/sunkern.bin"

	.align 2
Cry_Sunflora::
	.incbin "sound/direct_sound_samples/cries/sunflora.bin"

	.align 2
Cry_Yanma::
	.incbin "sound/direct_sound_samples/cries/yanma.bin"

	.align 2
Cry_Wooper::
	.incbin "sound/direct_sound_samples/cries/wooper.bin"

	.align 2
Cry_Quagsire::
	.incbin "sound/direct_sound_samples/cries/quagsire.bin"

	.align 2
Cry_Espeon::
	.incbin "sound/direct_sound_samples/cries/espeon.bin"

	.align 2
Cry_Umbreon::
	.incbin "sound/direct_sound_samples/cries/umbreon.bin"

	.align 2
Cry_Murkrow::
	.incbin "sound/direct_sound_samples/cries/murkrow.bin"

	.align 2
Cry_Slowking::
	.incbin "sound/direct_sound_samples/cries/slowking.bin"

	.align 2
Cry_Misdreavus::
	.incbin "sound/direct_sound_samples/cries/misdreavus.bin"

	.align 2
Cry_Unown::
	.incbin "sound/direct_sound_samples/cries/unown.bin"

	.align 2
Cry_Wobbuffet::
	.incbin "sound/direct_sound_samples/cries/wobbuffet.bin"

	.align 2
Cry_Girafarig::
	.incbin "sound/direct_sound_samples/cries/girafarig.bin"

	.align 2
Cry_Pineco::
	.incbin "sound/direct_sound_samples/cries/pineco.bin"

	.align 2
Cry_Forretress::
	.incbin "sound/direct_sound_samples/cries/forretress.bin"

	.align 2
Cry_Dunsparce::
	.incbin "sound/direct_sound_samples/cries/dunsparce.bin"

	.align 2
Cry_Gligar::
	.incbin "sound/direct_sound_samples/cries/gligar.bin"

	.align 2
Cry_Steelix::
	.incbin "sound/direct_sound_samples/cries/steelix.bin"

	.align 2
Cry_Snubbull::
	.incbin "sound/direct_sound_samples/cries/snubbull.bin"

	.align 2
Cry_Granbull::
	.incbin "sound/direct_sound_samples/cries/granbull.bin"

	.align 2
Cry_Qwilfish::
	.incbin "sound/direct_sound_samples/cries/qwilfish.bin"

	.align 2
Cry_Scizor::
	.incbin "sound/direct_sound_samples/cries/scizor.bin"

	.align 2
Cry_Shuckle::
	.incbin "sound/direct_sound_samples/cries/shuckle.bin"

	.align 2
Cry_Heracross::
	.incbin "sound/direct_sound_samples/cries/heracross.bin"

	.align 2
Cry_Sneasel::
	.incbin "sound/direct_sound_samples/cries/sneasel.bin"

	.align 2
Cry_Teddiursa::
	.incbin "sound/direct_sound_samples/cries/teddiursa.bin"

	.align 2
Cry_Ursaring::
	.incbin "sound/direct_sound_samples/cries/ursaring.bin"

	.align 2
Cry_Slugma::
	.incbin "sound/direct_sound_samples/cries/slugma.bin"

	.align 2
Cry_Magcargo::
	.incbin "sound/direct_sound_samples/cries/magcargo.bin"

	.align 2
Cry_Swinub::
	.incbin "sound/direct_sound_samples/cries/swinub.bin"

	.align 2
Cry_Piloswine::
	.incbin "sound/direct_sound_samples/cries/piloswine.bin"

	.align 2
Cry_Corsola::
	.incbin "sound/direct_sound_samples/cries/corsola.bin"

	.align 2
Cry_Remoraid::
	.incbin "sound/direct_sound_samples/cries/remoraid.bin"

	.align 2
Cry_Octillery::
	.incbin "sound/direct_sound_samples/cries/octillery.bin"

	.align 2
Cry_Delibird::
	.incbin "sound/direct_sound_samples/cries/delibird.bin"

	.align 2
Cry_Mantine::
	.incbin "sound/direct_sound_samples/cries/mantine.bin"

	.align 2
Cry_Skarmory::
	.incbin "sound/direct_sound_samples/cries/skarmory.bin"

	.align 2
Cry_Houndour::
	.incbin "sound/direct_sound_samples/cries/houndour.bin"

	.align 2
Cry_Houndoom::
	.incbin "sound/direct_sound_samples/cries/houndoom.bin"

	.align 2
Cry_Kingdra::
	.incbin "sound/direct_sound_samples/cries/kingdra.bin"

	.align 2
Cry_Phanpy::
	.incbin "sound/direct_sound_samples/cries/phanpy.bin"

	.align 2
Cry_Donphan::
	.incbin "sound/direct_sound_samples/cries/donphan.bin"

	.align 2
Cry_Porygon2::
	.incbin "sound/direct_sound_samples/cries/porygon2.bin"

	.align 2
Cry_Stantler::
	.incbin "sound/direct_sound_samples/cries/stantler.bin"

	.align 2
Cry_Smeargle::
	.incbin "sound/direct_sound_samples/cries/smeargle.bin"

	.align 2
Cry_Tyrogue::
	.incbin "sound/direct_sound_samples/cries/tyrogue.bin"

	.align 2
Cry_Hitmontop::
	.incbin "sound/direct_sound_samples/cries/hitmontop.bin"

	.align 2
Cry_Smoochum::
	.incbin "sound/direct_sound_samples/cries/smoochum.bin"

	.align 2
Cry_Elekid::
	.incbin "sound/direct_sound_samples/cries/elekid.bin"

	.align 2
Cry_Magby::
	.incbin "sound/direct_sound_samples/cries/magby.bin"

	.align 2
Cry_Miltank::
	.incbin "sound/direct_sound_samples/cries/miltank.bin"

	.align 2
Cry_Blissey::
	.incbin "sound/direct_sound_samples/cries/blissey.bin"

	.align 2
Cry_Raikou::
	.incbin "sound/direct_sound_samples/cries/raikou.bin"

	.align 2
Cry_Entei::
	.incbin "sound/direct_sound_samples/cries/entei.bin"

	.align 2
Cry_Suicune::
	.incbin "sound/direct_sound_samples/cries/suicune.bin"

	.align 2
Cry_Larvitar::
	.incbin "sound/direct_sound_samples/cries/larvitar.bin"

	.align 2
Cry_Pupitar::
	.incbin "sound/direct_sound_samples/cries/pupitar.bin"

	.align 2
Cry_Tyranitar::
	.incbin "sound/direct_sound_samples/cries/tyranitar.bin"

	.align 2
Cry_Lugia::
	.incbin "sound/direct_sound_samples/cries/lugia.bin"

	.align 2
Cry_HoOh::
	.incbin "sound/direct_sound_samples/cries/ho_oh.bin"

	.align 2
Cry_Celebi::
	.incbin "sound/direct_sound_samples/cries/celebi.bin"

	.align 2
Cry_Kecleon::
	.incbin "sound/direct_sound_samples/cries/kecleon.bin"

	.align 2
Cry_Roselia::
	.incbin "sound/direct_sound_samples/cries/roselia.bin"

	.align 2
Cry_Torkoal::
	.incbin "sound/direct_sound_samples/cries/torkoal.bin"

	.align 2
Cry_Electrike::
	.incbin "sound/direct_sound_samples/cries/electrike.bin"

	.align 2
Cry_Manectric::
	.incbin "sound/direct_sound_samples/cries/manectric.bin"

	.align 2
Cry_Duskull::
	.incbin "sound/direct_sound_samples/cries/duskull.bin"

	.align 2
Cry_Latias::
	.incbin "sound/direct_sound_samples/cries/latias.bin"

	.align 2
Cry_Wynaut::
	.incbin "sound/direct_sound_samples/cries/wynaut.bin"

	.align 2
Cry_Seviper::
	.incbin "sound/direct_sound_samples/cries/seviper.bin"

	.align 2
Cry_Sharpedo::
	.incbin "sound/direct_sound_samples/cries/sharpedo.bin"

	.align 2
Cry_Zangoose::
	.incbin "sound/direct_sound_samples/cries/zangoose.bin"

	.align 2
Cry_Azurill::
	.incbin "sound/direct_sound_samples/cries/azurill.bin"

	.align 2
Cry_Swablu::
	.incbin "sound/direct_sound_samples/cries/swablu.bin"

	.align 2
Cry_Altaria::
	.incbin "sound/direct_sound_samples/cries/altaria.bin"

	.align 2
Cry_Unused265::
	.incbin "sound/direct_sound_samples/cries/unused_265.bin"

	.align 2
Cry_Taillow::
	.incbin "sound/direct_sound_samples/cries/taillow.bin"

	.align 2
Cry_Swellow::
	.incbin "sound/direct_sound_samples/cries/swellow.bin"

	.align 2
Cry_Unused268::
	.incbin "sound/direct_sound_samples/cries/unused_268.bin"

	.align 2
Cry_Spinda::
	.incbin "sound/direct_sound_samples/cries/spinda.bin"

	.align 2
Cry_Torchic::
	.incbin "sound/direct_sound_samples/cries/torchic.bin"

	.align 2
Cry_Combusken::
	.incbin "sound/direct_sound_samples/cries/combusken.bin"

	.align 2
Cry_Blaziken::
	.incbin "sound/direct_sound_samples/cries/blaziken.bin"

	.align 2
Cry_Treecko::
	.incbin "sound/direct_sound_samples/cries/treecko.bin"

	.align 2
Cry_Grovyle::
	.incbin "sound/direct_sound_samples/cries/grovyle.bin"

	.align 2
Cry_Sceptile::
	.incbin "sound/direct_sound_samples/cries/sceptile.bin"

	.align 2
Cry_Mudkip::
	.incbin "sound/direct_sound_samples/cries/mudkip.bin"

	.align 2
Cry_Marshtomp::
	.incbin "sound/direct_sound_samples/cries/marshtomp.bin"

	.align 2
Cry_Swampert::
	.incbin "sound/direct_sound_samples/cries/swampert.bin"

	.align 2
Cry_Pelipper::
	.incbin "sound/direct_sound_samples/cries/pelipper.bin"

	.align 2
Cry_Wingull::
	.incbin "sound/direct_sound_samples/cries/wingull.bin"

	.align 2
Cry_Banette::
	.incbin "sound/direct_sound_samples/cries/banette.bin"

	.align 2
Cry_Shuppet::
	.incbin "sound/direct_sound_samples/cries/shuppet.bin"

	.align 2
Cry_Lotad::
	.incbin "sound/direct_sound_samples/cries/lotad.bin"

	.align 2
Cry_Lombre::
	.incbin "sound/direct_sound_samples/cries/lombre.bin"

	.align 2
Cry_Ludicolo::
	.incbin "sound/direct_sound_samples/cries/ludicolo.bin"

	.align 2
Cry_Seedot::
	.incbin "sound/direct_sound_samples/cries/seedot.bin"

	.align 2
Cry_Nuzleaf::
	.incbin "sound/direct_sound_samples/cries/nuzleaf.bin"

	.align 2
Cry_Shiftry::
	.incbin "sound/direct_sound_samples/cries/shiftry.bin"

	.align 2
Cry_Carvanha::
	.incbin "sound/direct_sound_samples/cries/carvanha.bin"

	.align 2
Cry_Wurmple::
	.incbin "sound/direct_sound_samples/cries/wurmple.bin"

	.align 2
Cry_Silcoon::
	.incbin "sound/direct_sound_samples/cries/silcoon.bin"

	.align 2
Cry_Beautifly::
	.incbin "sound/direct_sound_samples/cries/beautifly.bin"

	.align 2
Cry_Cascoon::
	.incbin "sound/direct_sound_samples/cries/cascoon.bin"

	.align 2
Cry_Dustox::
	.incbin "sound/direct_sound_samples/cries/dustox.bin"

	.align 2
Cry_Ralts::
	.incbin "sound/direct_sound_samples/cries/ralts.bin"

	.align 2
Cry_Kirlia::
	.incbin "sound/direct_sound_samples/cries/kirlia.bin"

	.align 2
Cry_Gardevoir::
	.incbin "sound/direct_sound_samples/cries/gardevoir.bin"

	.align 2
Cry_Slakoth::
	.incbin "sound/direct_sound_samples/cries/slakoth.bin"

	.align 2
Cry_Vigoroth::
	.incbin "sound/direct_sound_samples/cries/vigoroth.bin"

	.align 2
Cry_Slaking::
	.incbin "sound/direct_sound_samples/cries/slaking.bin"

	.align 2
Cry_Nincada::
	.incbin "sound/direct_sound_samples/cries/nincada.bin"

	.align 2
Cry_Ninjask::
	.incbin "sound/direct_sound_samples/cries/ninjask.bin"

	.align 2
Cry_Shedinja::
	.incbin "sound/direct_sound_samples/cries/shedinja.bin"

	.align 2
Cry_Makuhita::
	.incbin "sound/direct_sound_samples/cries/makuhita.bin"

	.align 2
Cry_Hariyama::
	.incbin "sound/direct_sound_samples/cries/hariyama.bin"

	.align 2
Cry_Nosepass::
	.incbin "sound/direct_sound_samples/cries/nosepass.bin"

	.align 2
Cry_Glalie::
	.incbin "sound/direct_sound_samples/cries/glalie.bin"

	.align 2
Cry_Plusle::
	.incbin "sound/direct_sound_samples/cries/plusle.bin"

	.align 2
Cry_Minun::
	.incbin "sound/direct_sound_samples/cries/minun.bin"

	.align 2
Cry_Surskit::
	.incbin "sound/direct_sound_samples/cries/surskit.bin"

	.align 2
Cry_Masquerain::
	.incbin "sound/direct_sound_samples/cries/masquerain.bin"

	.align 2
Cry_Skitty::
	.incbin "sound/direct_sound_samples/cries/skitty.bin"

	.align 2
Cry_Delcatty::
	.incbin "sound/direct_sound_samples/cries/delcatty.bin"

	.align 2
Cry_Gulpin::
	.incbin "sound/direct_sound_samples/cries/gulpin.bin"

	.align 2
Cry_Swalot::
	.incbin "sound/direct_sound_samples/cries/swalot.bin"

	.align 2
Cry_Numel::
	.incbin "sound/direct_sound_samples/cries/numel.bin"

	.align 2
Cry_Camerupt::
	.incbin "sound/direct_sound_samples/cries/camerupt.bin"

	.align 2
Cry_Barboach::
	.incbin "sound/direct_sound_samples/cries/barboach.bin"

	.align 2
Cry_Whiscash::
	.incbin "sound/direct_sound_samples/cries/whiscash.bin"

	.align 2
Cry_Corphish::
	.incbin "sound/direct_sound_samples/cries/corphish.bin"

	.align 2
Cry_Crawdaunt::
	.incbin "sound/direct_sound_samples/cries/crawdaunt.bin"

	.align 2
Cry_Spoink::
	.incbin "sound/direct_sound_samples/cries/spoink.bin"

	.align 2
Cry_Grumpig::
	.incbin "sound/direct_sound_samples/cries/grumpig.bin"

	.align 2
Cry_Trapinch::
	.incbin "sound/direct_sound_samples/cries/trapinch.bin"

	.align 2
Cry_Vibrava::
	.incbin "sound/direct_sound_samples/cries/vibrava.bin"

	.align 2
Cry_Flygon::
	.incbin "sound/direct_sound_samples/cries/flygon.bin"

	.align 2
Cry_Cacnea::
	.incbin "sound/direct_sound_samples/cries/cacnea.bin"

	.align 2
Cry_Cacturne::
	.incbin "sound/direct_sound_samples/cries/cacturne.bin"

	.align 2
Cry_Baltoy::
	.incbin "sound/direct_sound_samples/cries/baltoy.bin"

	.align 2
Cry_Claydol::
	.incbin "sound/direct_sound_samples/cries/claydol.bin"

	.align 2
Cry_Lunatone::
	.incbin "sound/direct_sound_samples/cries/lunatone.bin"

	.align 2
Cry_Solrock::
	.incbin "sound/direct_sound_samples/cries/solrock.bin"

	.align 2
Cry_Feebas::
	.incbin "sound/direct_sound_samples/cries/feebas.bin"

	.align 2
Cry_Milotic::
	.incbin "sound/direct_sound_samples/cries/milotic.bin"

	.align 2
Cry_Absol::
	.incbin "sound/direct_sound_samples/cries/absol.bin"

	.align 2
Cry_Meditite::
	.incbin "sound/direct_sound_samples/cries/meditite.bin"

	.align 2
Cry_Medicham::
	.incbin "sound/direct_sound_samples/cries/medicham.bin"

	.align 2
Cry_Spheal::
	.incbin "sound/direct_sound_samples/cries/spheal.bin"

	.align 2
Cry_Sealeo::
	.incbin "sound/direct_sound_samples/cries/sealeo.bin"

	.align 2
Cry_Walrein::
	.incbin "sound/direct_sound_samples/cries/walrein.bin"

	.align 2
Cry_Clamperl::
	.incbin "sound/direct_sound_samples/cries/clamperl.bin"

	.align 2
Cry_Huntail::
	.incbin "sound/direct_sound_samples/cries/huntail.bin"

	.align 2
Cry_Gorebyss::
	.incbin "sound/direct_sound_samples/cries/gorebyss.bin"

	.align 2
Cry_Lileep::
	.incbin "sound/direct_sound_samples/cries/lileep.bin"

	.align 2
Cry_Cradily::
	.incbin "sound/direct_sound_samples/cries/cradily.bin"

	.align 2
Cry_Anorith::
	.incbin "sound/direct_sound_samples/cries/anorith.bin"

	.align 2
Cry_Armaldo::
	.incbin "sound/direct_sound_samples/cries/armaldo.bin"

	.align 2
Cry_Beldum::
	.incbin "sound/direct_sound_samples/cries/beldum.bin"

	.align 2
Cry_Metang::
	.incbin "sound/direct_sound_samples/cries/metang.bin"

	.align 2
Cry_Metagross::
	.incbin "sound/direct_sound_samples/cries/metagross.bin"

	.align 2
Cry_Bagon::
	.incbin "sound/direct_sound_samples/cries/bagon.bin"

	.align 2
Cry_Shelgon::
	.incbin "sound/direct_sound_samples/cries/shelgon.bin"

	.align 2
Cry_Regirock::
	.incbin "sound/direct_sound_samples/cries/regirock.bin"

	.align 2
Cry_Regice::
	.incbin "sound/direct_sound_samples/cries/regice.bin"

	.align 2
Cry_Registeel::
	.incbin "sound/direct_sound_samples/cries/registeel.bin"

	.align 2
Cry_Castform::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Volbeat::
	.incbin "sound/direct_sound_samples/cries/volbeat.bin"

	.align 2
Cry_Illumise::
	.incbin "sound/direct_sound_samples/cries/illumise.bin"

	.align 2
Cry_Poochyena::
	.incbin "sound/direct_sound_samples/cries/poochyena.bin"

	.align 2
Cry_Mightyena::
	.incbin "sound/direct_sound_samples/cries/mightyena.bin"

	.align 2
Cry_Dusclops::
	.incbin "sound/direct_sound_samples/cries/dusclops.bin"

	.align 2
Cry_Sableye::
	.incbin "sound/direct_sound_samples/cries/sableye.bin"

	.align 2
Cry_Mawile::
	.incbin "sound/direct_sound_samples/cries/mawile.bin"

	.align 2
Cry_Aron::
	.incbin "sound/direct_sound_samples/cries/aron.bin"

	.align 2
Cry_Lairon::
	.incbin "sound/direct_sound_samples/cries/lairon.bin"

	.align 2
Cry_Aggron::
	.incbin "sound/direct_sound_samples/cries/aggron.bin"

	.align 2
Cry_Relicanth::
	.incbin "sound/direct_sound_samples/cries/relicanth.bin"

	.align 2
Cry_Luvdisc::
	.incbin "sound/direct_sound_samples/cries/luvdisc.bin"

	.align 2
Cry_Groudon::
	.incbin "sound/direct_sound_samples/cries/groudon.bin"

	.align 2
Cry_Kyogre::
	.incbin "sound/direct_sound_samples/cries/kyogre.bin"

	.align 2
Cry_Rayquaza::
	.incbin "sound/direct_sound_samples/cries/rayquaza.bin"

	.align 2
Cry_Salamence::
	.incbin "sound/direct_sound_samples/cries/salamence.bin"

	.align 2
Cry_Breloom::
	.incbin "sound/direct_sound_samples/cries/breloom.bin"

	.align 2
Cry_Shroomish::
	.incbin "sound/direct_sound_samples/cries/shroomish.bin"

	.align 2
Cry_Linoone::
	.incbin "sound/direct_sound_samples/cries/linoone.bin"

	.align 2
Cry_Tropius::
	.incbin "sound/direct_sound_samples/cries/tropius.bin"

	.align 2
Cry_Wailmer::
	.incbin "sound/direct_sound_samples/cries/wailmer.bin"

	.align 2
Cry_Zigzagoon::
	.incbin "sound/direct_sound_samples/cries/zigzagoon.bin"

	.align 2
Cry_Exploud::
	.incbin "sound/direct_sound_samples/cries/exploud.bin"

	.align 2
Cry_Loudred::
	.incbin "sound/direct_sound_samples/cries/loudred.bin"

	.align 2
Cry_Wailord::
	.incbin "sound/direct_sound_samples/cries/wailord.bin"

	.align 2
Cry_Whismur::
	.incbin "sound/direct_sound_samples/cries/whismur.bin"

	.align 2
Cry_Snorunt::
	.incbin "sound/direct_sound_samples/cries/snorunt.bin"

	.align 2
Cry_Latios::
	.incbin "sound/direct_sound_samples/cries/latios.bin"

	.align 2
Cry_Jirachi::
	.incbin "sound/direct_sound_samples/cries/jirachi.bin"

	.align 2
Cry_Deoxys::
	.incbin "sound/direct_sound_samples/cries/deoxys.bin"

	.align 2
Cry_Chimecho::
	.incbin "sound/direct_sound_samples/cries/chimecho.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_unknown_18::
	.incbin "sound/direct_sound_samples/unknown_18.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_Phoneme_1::
	.incbin "sound/direct_sound_samples/phonemes/01.bin"

	.align 2
DirectSoundWaveData_Phoneme_2::
	.incbin "sound/direct_sound_samples/phonemes/02.bin"

	.align 2
DirectSoundWaveData_Phoneme_3::
	.incbin "sound/direct_sound_samples/phonemes/03.bin"

	.align 2
DirectSoundWaveData_Phoneme_4::
	.incbin "sound/direct_sound_samples/phonemes/04.bin"

	.align 2
DirectSoundWaveData_Phoneme_5::
	.incbin "sound/direct_sound_samples/phonemes/05.bin"

	.align 2
DirectSoundWaveData_Phoneme_6::
	.incbin "sound/direct_sound_samples/phonemes/06.bin"

	.align 2
DirectSoundWaveData_Phoneme_7::
	.incbin "sound/direct_sound_samples/phonemes/07.bin"

	.align 2
DirectSoundWaveData_Phoneme_8::
	.incbin "sound/direct_sound_samples/phonemes/08.bin"

	.align 2
DirectSoundWaveData_Phoneme_9::
	.incbin "sound/direct_sound_samples/phonemes/09.bin"

	.align 2
DirectSoundWaveData_Phoneme_10::
	.incbin "sound/direct_sound_samples/phonemes/10.bin"

	.align 2
DirectSoundWaveData_Phoneme_11::
	.incbin "sound/direct_sound_samples/phonemes/11.bin"

	.align 2
DirectSoundWaveData_Phoneme_12::
	.incbin "sound/direct_sound_samples/phonemes/12.bin"

	.align 2
DirectSoundWaveData_Phoneme_13::
	.incbin "sound/direct_sound_samples/phonemes/13.bin"

	.align 2
DirectSoundWaveData_Phoneme_14::
	.incbin "sound/direct_sound_samples/phonemes/14.bin"

	.align 2
DirectSoundWaveData_Phoneme_15::
	.incbin "sound/direct_sound_samples/phonemes/15.bin"

	.align 2
DirectSoundWaveData_Phoneme_16::
	.incbin "sound/direct_sound_samples/phonemes/16.bin"

	.align 2
DirectSoundWaveData_Phoneme_17::
	.incbin "sound/direct_sound_samples/phonemes/17.bin"

	.align 2
DirectSoundWaveData_Phoneme_18::
	.incbin "sound/direct_sound_samples/phonemes/18.bin"

	.align 2
DirectSoundWaveData_Phoneme_19::
	.incbin "sound/direct_sound_samples/phonemes/19.bin"

	.align 2
DirectSoundWaveData_Phoneme_20::
	.incbin "sound/direct_sound_samples/phonemes/20.bin"

	.align 2
DirectSoundWaveData_Phoneme_21::
	.incbin "sound/direct_sound_samples/phonemes/21.bin"

	.align 2
DirectSoundWaveData_Phoneme_22::
	.incbin "sound/direct_sound_samples/phonemes/22.bin"

	.align 2
DirectSoundWaveData_Phoneme_23::
	.incbin "sound/direct_sound_samples/phonemes/23.bin"

	.align 2
DirectSoundWaveData_Phoneme_24::
	.incbin "sound/direct_sound_samples/phonemes/24.bin"

	.align 2
DirectSoundWaveData_Phoneme_25::
	.incbin "sound/direct_sound_samples/phonemes/25.bin"

	.align 2
DirectSoundWaveData_Phoneme_26::
	.incbin "sound/direct_sound_samples/phonemes/26.bin"

	.align 2
DirectSoundWaveData_Phoneme_27::
	.incbin "sound/direct_sound_samples/phonemes/27.bin"

	.align 2
DirectSoundWaveData_Phoneme_28::
	.incbin "sound/direct_sound_samples/phonemes/28.bin"

	.align 2
DirectSoundWaveData_Phoneme_29::
	.incbin "sound/direct_sound_samples/phonemes/29.bin"

	.align 2
DirectSoundWaveData_Phoneme_30::
	.incbin "sound/direct_sound_samples/phonemes/30.bin"

	.align 2
DirectSoundWaveData_Phoneme_31::
	.incbin "sound/direct_sound_samples/phonemes/31.bin"

	.align 2
DirectSoundWaveData_Phoneme_32::
	.incbin "sound/direct_sound_samples/phonemes/32.bin"

	.align 2
DirectSoundWaveData_Phoneme_33::
	.incbin "sound/direct_sound_samples/phonemes/33.bin"

	.align 2
DirectSoundWaveData_Phoneme_34::
	.incbin "sound/direct_sound_samples/phonemes/34.bin"

	.align 2
DirectSoundWaveData_Phoneme_35::
	.incbin "sound/direct_sound_samples/phonemes/35.bin"

	.align 2
DirectSoundWaveData_Phoneme_36::
	.incbin "sound/direct_sound_samples/phonemes/36.bin"

	.align 2
DirectSoundWaveData_Phoneme_37::
	.incbin "sound/direct_sound_samples/phonemes/37.bin"

	.align 2
DirectSoundWaveData_Phoneme_38::
	.incbin "sound/direct_sound_samples/phonemes/38.bin"

	.align 2
DirectSoundWaveData_Phoneme_39::
	.incbin "sound/direct_sound_samples/phonemes/39.bin"

	.align 2
DirectSoundWaveData_Phoneme_40::
	.incbin "sound/direct_sound_samples/phonemes/40.bin"

	.align 2
DirectSoundWaveData_Phoneme_41::
	.incbin "sound/direct_sound_samples/phonemes/41.bin"

	.align 2
DirectSoundWaveData_Phoneme_42::
	.incbin "sound/direct_sound_samples/phonemes/42.bin"

	.align 2
DirectSoundWaveData_Phoneme_43::
	.incbin "sound/direct_sound_samples/phonemes/43.bin"

	.align 2
DirectSoundWaveData_Phoneme_44::
	.incbin "sound/direct_sound_samples/phonemes/44.bin"

	.align 2
DirectSoundWaveData_Phoneme_45::
	.incbin "sound/direct_sound_samples/phonemes/45.bin"

	.align 2
DirectSoundWaveData_Phoneme_46::
	.incbin "sound/direct_sound_samples/phonemes/46.bin"

	.align 2
DirectSoundWaveData_Phoneme_47::
	.incbin "sound/direct_sound_samples/phonemes/47.bin"

	.align 2
DirectSoundWaveData_Phoneme_48::
	.incbin "sound/direct_sound_samples/phonemes/48.bin"

	.align 2
DirectSoundWaveData_Phoneme_49::
	.incbin "sound/direct_sound_samples/phonemes/49.bin"

	.align 2
DirectSoundWaveData_Phoneme_50::
	.incbin "sound/direct_sound_samples/phonemes/50.bin"

	.align 2
DirectSoundWaveData_Phoneme_51::
	.incbin "sound/direct_sound_samples/phonemes/51.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"

	.align 2
DirectSoundWaveData_101BS35::
	.incbin "sound/direct_sound_samples/gswavetable/101BS35.bin"

	.align 2
DirectSoundWaveData_101BS48::
	.incbin "sound/direct_sound_samples/gswavetable/101BS48.bin"

	.align 2
DirectSoundWaveData_12STR55A::
	.incbin "sound/direct_sound_samples/gswavetable/12STR55A.bin"

	.align 2
DirectSoundWaveData_12STR79A::
	.incbin "sound/direct_sound_samples/gswavetable/12STR79A.bin"

	.align 2
DirectSoundWaveData_12STR89A::
	.incbin "sound/direct_sound_samples/gswavetable/12STR89A.bin"

	.align 2
DirectSoundWaveData_5_SAW81::
	.incbin "sound/direct_sound_samples/gswavetable/5_SAW81.bin"

	.align 2
DirectSoundWaveData_60ORG67::
	.incbin "sound/direct_sound_samples/gswavetable/60ORG67.bin"

	.align 2
DirectSoundWaveData_60ORG91::
	.incbin "sound/direct_sound_samples/gswavetable/60ORG91.bin"

	.align 2
DirectSoundWaveData_60ORG96::
	.incbin "sound/direct_sound_samples/gswavetable/60ORG96.bin"

	.align 2
DirectSoundWaveData_60PNO43::
	.incbin "sound/direct_sound_samples/gswavetable/60PNO43.bin"

	.align 2
DirectSoundWaveData_60PNO48::
	.incbin "sound/direct_sound_samples/gswavetable/60PNO48.bin"

	.align 2
DirectSoundWaveData_60PNO58::
	.incbin "sound/direct_sound_samples/gswavetable/60PNO58.bin"

	.align 2
DirectSoundWaveData_60PNO66::
	.incbin "sound/direct_sound_samples/gswavetable/60PNO66.bin"

	.align 2
DirectSoundWaveData_60PNO80::
	.incbin "sound/direct_sound_samples/gswavetable/60PNO80.bin"

	.align 2
DirectSoundWaveData_60PNO86::
	.incbin "sound/direct_sound_samples/gswavetable/60PNO86.bin"

	.align 2
DirectSoundWaveData_60PNO92::
	.incbin "sound/direct_sound_samples/gswavetable/60PNO92.bin"

	.align 2
DirectSoundWaveData_808CW64::
	.incbin "sound/direct_sound_samples/gswavetable/808CW64.bin"

	.align 2
DirectSoundWaveData_808MC64::
	.incbin "sound/direct_sound_samples/gswavetable/808MC64.bin"

	.align 2
DirectSoundWaveData_808OH60A::
	.incbin "sound/direct_sound_samples/gswavetable/808OH60A.bin"

	.align 2
DirectSoundWaveData_808SD60::
	.incbin "sound/direct_sound_samples/gswavetable/808SD60.bin"

	.align 2
DirectSoundWaveData_ACCFR68A::
	.incbin "sound/direct_sound_samples/gswavetable/ACCFR68A.bin"

	.align 2
DirectSoundWaveData_ACCFR96A::
	.incbin "sound/direct_sound_samples/gswavetable/ACCFR96A.bin"

	.align 2
DirectSoundWaveData_ACOBS32A::
	.incbin "sound/direct_sound_samples/gswavetable/ACOBS32A.bin"

	.align 2
DirectSoundWaveData_ACOBS43A::
	.incbin "sound/direct_sound_samples/gswavetable/ACOBS43A.bin"

	.align 2
DirectSoundWaveData_ACOBS60A::
	.incbin "sound/direct_sound_samples/gswavetable/ACOBS60A.bin"

	.align 2
DirectSoundWaveData_AGOGO60::
	.incbin "sound/direct_sound_samples/gswavetable/AGOGO60.bin"

	.align 2
DirectSoundWaveData_APPLS64A::
	.incbin "sound/direct_sound_samples/gswavetable/APPLS64A.bin"

	.align 2
DirectSoundWaveData_ATMOS60A::
	.incbin "sound/direct_sound_samples/gswavetable/ATMOS60A.bin"

	.align 2
DirectSoundWaveData_ATMOS84::
	.incbin "sound/direct_sound_samples/gswavetable/ATMOS84.bin"

	.align 2
DirectSoundWaveData_A_SAX53::
	.incbin "sound/direct_sound_samples/gswavetable/A_SAX53.bin"

	.align 2
DirectSoundWaveData_A_SAX59::
	.incbin "sound/direct_sound_samples/gswavetable/A_SAX59.bin"

	.align 2
DirectSoundWaveData_A_SAX63::
	.incbin "sound/direct_sound_samples/gswavetable/A_SAX63.bin"

	.align 2
DirectSoundWaveData_A_SAX69::
	.incbin "sound/direct_sound_samples/gswavetable/A_SAX69.bin"

	.align 2
DirectSoundWaveData_A_SAX77::
	.incbin "sound/direct_sound_samples/gswavetable/A_SAX77.bin"

	.align 2
DirectSoundWaveData_A_SAX87::
	.incbin "sound/direct_sound_samples/gswavetable/A_SAX87.bin"

	.align 2
DirectSoundWaveData_A_SAX96::
	.incbin "sound/direct_sound_samples/gswavetable/A_SAX96.bin"

	.align 2
DirectSoundWaveData_A_SAXA5::
	.incbin "sound/direct_sound_samples/gswavetable/A_SAXA5.bin"

	.align 2
DirectSoundWaveData_BAGPP53A::
	.incbin "sound/direct_sound_samples/gswavetable/BAGPP53A.bin"

	.align 2
DirectSoundWaveData_BAGPP64A::
	.incbin "sound/direct_sound_samples/gswavetable/BAGPP64A.bin"

	.align 2
DirectSoundWaveData_BAGPP74A::
	.incbin "sound/direct_sound_samples/gswavetable/BAGPP74A.bin"

	.align 2
DirectSoundWaveData_BAGPP84A::
	.incbin "sound/direct_sound_samples/gswavetable/BAGPP84A.bin"

	.align 2
DirectSoundWaveData_BAGPP93A::
	.incbin "sound/direct_sound_samples/gswavetable/BAGPP93A.bin"

	.align 2
DirectSoundWaveData_BANDO64::
	.incbin "sound/direct_sound_samples/gswavetable/BANDO64.bin"

	.align 2
DirectSoundWaveData_BANDO74::
	.incbin "sound/direct_sound_samples/gswavetable/BANDO74.bin"

	.align 2
DirectSoundWaveData_BANJO60::
	.incbin "sound/direct_sound_samples/gswavetable/BANJO60.bin"

	.align 2
DirectSoundWaveData_BANJO70::
	.incbin "sound/direct_sound_samples/gswavetable/BANJO70.bin"

	.align 2
DirectSoundWaveData_BANJO83::
	.incbin "sound/direct_sound_samples/gswavetable/BANJO83.bin"

	.align 2
DirectSoundWaveData_BASSN44::
	.incbin "sound/direct_sound_samples/gswavetable/BASSN44.bin"

	.align 2
DirectSoundWaveData_BASSN69::
	.incbin "sound/direct_sound_samples/gswavetable/BASSN69.bin"

	.align 2
DirectSoundWaveData_BELTR60::
	.incbin "sound/direct_sound_samples/gswavetable/BELTR60.bin"

	.align 2
DirectSoundWaveData_BIRD_60::
	.incbin "sound/direct_sound_samples/gswavetable/BIRD_60.bin"

	.align 2
DirectSoundWaveData_BOTTL72::
	.incbin "sound/direct_sound_samples/gswavetable/BOTTL72.bin"

	.align 2
DirectSoundWaveData_BOTTL84::
	.incbin "sound/direct_sound_samples/gswavetable/BOTTL84.bin"

	.align 2
DirectSoundWaveData_BRASS64::
	.incbin "sound/direct_sound_samples/gswavetable/BRASS64.bin"

	.align 2
DirectSoundWaveData_BRASS72A::
	.incbin "sound/direct_sound_samples/gswavetable/BRASS72A.bin"

	.align 2
DirectSoundWaveData_BRASS84A::
	.incbin "sound/direct_sound_samples/gswavetable/BRASS84A.bin"

	.align 2
DirectSoundWaveData_BRASS96A::
	.incbin "sound/direct_sound_samples/gswavetable/BRASS96A.bin"

	.align 2
DirectSoundWaveData_BSLAP60::
	.incbin "sound/direct_sound_samples/gswavetable/BSLAP60.bin"

	.align 2
DirectSoundWaveData_BSWRL60::
	.incbin "sound/direct_sound_samples/gswavetable/BSWRL60.bin"

	.align 2
DirectSoundWaveData_BS_LD48::
	.incbin "sound/direct_sound_samples/gswavetable/BS_LD48.bin"

	.align 2
DirectSoundWaveData_BS_LD72::
	.incbin "sound/direct_sound_samples/gswavetable/BS_LD72.bin"

	.align 2
DirectSoundWaveData_BS_LD96::
	.incbin "sound/direct_sound_samples/gswavetable/BS_LD96.bin"

	.align 2
DirectSoundWaveData_BUBLE68A::
	.incbin "sound/direct_sound_samples/gswavetable/BUBLE68A.bin"

	.align 2
DirectSoundWaveData_BURST64A::
	.incbin "sound/direct_sound_samples/gswavetable/BURST64A.bin"

	.align 2
DirectSoundWaveData_B_SAX38::
	.incbin "sound/direct_sound_samples/gswavetable/B_SAX38.bin"

	.align 2
DirectSoundWaveData_B_SAX48::
	.incbin "sound/direct_sound_samples/gswavetable/B_SAX48.bin"

	.align 2
DirectSoundWaveData_B_SAX59::
	.incbin "sound/direct_sound_samples/gswavetable/B_SAX59.bin"

	.align 2
DirectSoundWaveData_B_SAX86::
	.incbin "sound/direct_sound_samples/gswavetable/B_SAX86.bin"

	.align 2
DirectSoundWaveData_B_SAXB0A::
	.incbin "sound/direct_sound_samples/gswavetable/B_SAXB0A.bin"

	.align 2
DirectSoundWaveData_B_TAP64::
	.incbin "sound/direct_sound_samples/gswavetable/B_TAP64.bin"

	.align 2
DirectSoundWaveData_CABA_60::
	.incbin "sound/direct_sound_samples/gswavetable/CABA_60.bin"

	.align 2
DirectSoundWaveData_CALLI72::
	.incbin "sound/direct_sound_samples/gswavetable/CALLI72.bin"

	.align 2
DirectSoundWaveData_CALLI84::
	.incbin "sound/direct_sound_samples/gswavetable/CALLI84.bin"

	.align 2
DirectSoundWaveData_CAST_60::
	.incbin "sound/direct_sound_samples/gswavetable/CAST_60.bin"

	.align 2
DirectSoundWaveData_CELLH64::
	.incbin "sound/direct_sound_samples/gswavetable/CELLH64.bin"

	.align 2
DirectSoundWaveData_CELLL64::
	.incbin "sound/direct_sound_samples/gswavetable/CELLL64.bin"

	.align 2
DirectSoundWaveData_CELLO28::
	.incbin "sound/direct_sound_samples/gswavetable/CELLO28.bin"

	.align 2
DirectSoundWaveData_CELLO41::
	.incbin "sound/direct_sound_samples/gswavetable/CELLO41.bin"

	.align 2
DirectSoundWaveData_CELLO76::
	.incbin "sound/direct_sound_samples/gswavetable/CELLO76.bin"

	.align 2
DirectSoundWaveData_CELST77::
	.incbin "sound/direct_sound_samples/gswavetable/CELST77.bin"

	.align 2
DirectSoundWaveData_CELSTA1::
	.incbin "sound/direct_sound_samples/gswavetable/CELSTA1.bin"

	.align 2
DirectSoundWaveData_CHFFR72A::
	.incbin "sound/direct_sound_samples/gswavetable/CHFFR72A.bin"

	.align 2
DirectSoundWaveData_CHFFR84::
	.incbin "sound/direct_sound_samples/gswavetable/CHFFR84.bin"

	.align 2
DirectSoundWaveData_CHH__60A::
	.incbin "sound/direct_sound_samples/gswavetable/CHH__60A.bin"

	.align 2
DirectSoundWaveData_CHINA60A::
	.incbin "sound/direct_sound_samples/gswavetable/CHINA60A.bin"

	.align 2
DirectSoundWaveData_CHOIR65A::
	.incbin "sound/direct_sound_samples/gswavetable/CHOIR65A.bin"

	.align 2
DirectSoundWaveData_CHRNG60::
	.incbin "sound/direct_sound_samples/gswavetable/CHRNG60.bin"

	.align 2
DirectSoundWaveData_CHRNG84::
	.incbin "sound/direct_sound_samples/gswavetable/CHRNG84.bin"

	.align 2
DirectSoundWaveData_CLAVE60::
	.incbin "sound/direct_sound_samples/gswavetable/CLAVE60.bin"

	.align 2
DirectSoundWaveData_CLAVI48::
	.incbin "sound/direct_sound_samples/gswavetable/CLAVI48.bin"

	.align 2
DirectSoundWaveData_CLAVI60::
	.incbin "sound/direct_sound_samples/gswavetable/CLAVI60.bin"

	.align 2
DirectSoundWaveData_CLAVI72::
	.incbin "sound/direct_sound_samples/gswavetable/CLAVI72.bin"

	.align 2
DirectSoundWaveData_CLAVI84::
	.incbin "sound/direct_sound_samples/gswavetable/CLAVI84.bin"

	.align 2
DirectSoundWaveData_CLICK60::
	.incbin "sound/direct_sound_samples/gswavetable/CLICK60.bin"

	.align 2
DirectSoundWaveData_CLNGT48::
	.incbin "sound/direct_sound_samples/gswavetable/CLNGT48.bin"

	.align 2
DirectSoundWaveData_CLNGT60::
	.incbin "sound/direct_sound_samples/gswavetable/CLNGT60.bin"

	.align 2
DirectSoundWaveData_CLNGT67::
	.incbin "sound/direct_sound_samples/gswavetable/CLNGT67.bin"

	.align 2
DirectSoundWaveData_CLNGT72::
	.incbin "sound/direct_sound_samples/gswavetable/CLNGT72.bin"

	.align 2
DirectSoundWaveData_CLNGT84::
	.incbin "sound/direct_sound_samples/gswavetable/CLNGT84.bin"

	.align 2
DirectSoundWaveData_CONBH41::
	.incbin "sound/direct_sound_samples/gswavetable/CONBH41.bin"

	.align 2
DirectSoundWaveData_CONBL41::
	.incbin "sound/direct_sound_samples/gswavetable/CONBL41.bin"

	.align 2
DirectSoundWaveData_CONBS28::
	.incbin "sound/direct_sound_samples/gswavetable/CONBS28.bin"

	.align 2
DirectSoundWaveData_COS__59::
	.incbin "sound/direct_sound_samples/gswavetable/COS__59.bin"

	.align 2
DirectSoundWaveData_COS__76::
	.incbin "sound/direct_sound_samples/gswavetable/COS__76.bin"

	.align 2
DirectSoundWaveData_COWBL66::
	.incbin "sound/direct_sound_samples/gswavetable/COWBL66.bin"

	.align 2
DirectSoundWaveData_CPASS64::
	.incbin "sound/direct_sound_samples/gswavetable/CPASS64.bin"

	.align 2
DirectSoundWaveData_CRASH60B::
	.incbin "sound/direct_sound_samples/gswavetable/CRASH60B.bin"

	.align 2
DirectSoundWaveData_CRASH65::
	.incbin "sound/direct_sound_samples/gswavetable/CRASH65.bin"

	.align 2
DirectSoundWaveData_CREAK64::
	.incbin "sound/direct_sound_samples/gswavetable/CREAK64.bin"

	.align 2
DirectSoundWaveData_CSTOP64::
	.incbin "sound/direct_sound_samples/gswavetable/CSTOP64.bin"

	.align 2
DirectSoundWaveData_C_ORG46A::
	.incbin "sound/direct_sound_samples/gswavetable/C_ORG46A.bin"

	.align 2
DirectSoundWaveData_C_ORG56A::
	.incbin "sound/direct_sound_samples/gswavetable/C_ORG56A.bin"

	.align 2
DirectSoundWaveData_C_ORG66A::
	.incbin "sound/direct_sound_samples/gswavetable/C_ORG66A.bin"

	.align 2
DirectSoundWaveData_C_ORG78A::
	.incbin "sound/direct_sound_samples/gswavetable/C_ORG78A.bin"

	.align 2
DirectSoundWaveData_C_ORG90A::
	.incbin "sound/direct_sound_samples/gswavetable/C_ORG90A.bin"

	.align 2
DirectSoundWaveData_DELP160A::
	.incbin "sound/direct_sound_samples/gswavetable/DELP160A.bin"

	.align 2
DirectSoundWaveData_DELP184A::
	.incbin "sound/direct_sound_samples/gswavetable/DELP184A.bin"

	.align 2
DirectSoundWaveData_DELP278::
	.incbin "sound/direct_sound_samples/gswavetable/DELP278.bin"

	.align 2
DirectSoundWaveData_DOCSL53::
	.incbin "sound/direct_sound_samples/gswavetable/DOCSL53.bin"

	.align 2
DirectSoundWaveData_DOCSL77::
	.incbin "sound/direct_sound_samples/gswavetable/DOCSL77.bin"

	.align 2
DirectSoundWaveData_DOGBW60::
	.incbin "sound/direct_sound_samples/gswavetable/DOGBW60.bin"

	.align 2
DirectSoundWaveData_DORG190::
	.incbin "sound/direct_sound_samples/gswavetable/DORG190.bin"

	.align 2
DirectSoundWaveData_DSTGT48::
	.incbin "sound/direct_sound_samples/gswavetable/DSTGT48.bin"

	.align 2
DirectSoundWaveData_DSTGT54::
	.incbin "sound/direct_sound_samples/gswavetable/DSTGT54.bin"

	.align 2
DirectSoundWaveData_DSTGT59::
	.incbin "sound/direct_sound_samples/gswavetable/DSTGT59.bin"

	.align 2
DirectSoundWaveData_DSTGT64::
	.incbin "sound/direct_sound_samples/gswavetable/DSTGT64.bin"

	.align 2
DirectSoundWaveData_DSTGT71::
	.incbin "sound/direct_sound_samples/gswavetable/DSTGT71.bin"

	.align 2
DirectSoundWaveData_DSTGT77::
	.incbin "sound/direct_sound_samples/gswavetable/DSTGT77.bin"

	.align 2
DirectSoundWaveData_DSTGT92::
	.incbin "sound/direct_sound_samples/gswavetable/DSTGT92.bin"

	.align 2
DirectSoundWaveData_DSTGTA1::
	.incbin "sound/direct_sound_samples/gswavetable/DSTGTA1.bin"

	.align 2
DirectSoundWaveData_DSTGTA9::
	.incbin "sound/direct_sound_samples/gswavetable/DSTGTA9.bin"

	.align 2
DirectSoundWaveData_DWCUT60::
	.incbin "sound/direct_sound_samples/gswavetable/DWCUT60.bin"

	.align 2
DirectSoundWaveData_EHORN53A::
	.incbin "sound/direct_sound_samples/gswavetable/EHORN53A.bin"

	.align 2
DirectSoundWaveData_EHORN61A::
	.incbin "sound/direct_sound_samples/gswavetable/EHORN61A.bin"

	.align 2
DirectSoundWaveData_EHORN70A::
	.incbin "sound/direct_sound_samples/gswavetable/EHORN70A.bin"

	.align 2
DirectSoundWaveData_EHORN82A::
	.incbin "sound/direct_sound_samples/gswavetable/EHORN82A.bin"

	.align 2
DirectSoundWaveData_ELESD60A::
	.incbin "sound/direct_sound_samples/gswavetable/ELESD60A.bin"

	.align 2
DirectSoundWaveData_ELP1_49::
	.incbin "sound/direct_sound_samples/gswavetable/ELP1_49.bin"

	.align 2
DirectSoundWaveData_ELP1_56::
	.incbin "sound/direct_sound_samples/gswavetable/ELP1_56.bin"

	.align 2
DirectSoundWaveData_ELP1_67::
	.incbin "sound/direct_sound_samples/gswavetable/ELP1_67.bin"

	.align 2
DirectSoundWaveData_ELP1_80::
	.incbin "sound/direct_sound_samples/gswavetable/ELP1_80.bin"

	.align 2
DirectSoundWaveData_ELP1_97::
	.incbin "sound/direct_sound_samples/gswavetable/ELP1_97.bin"

	.align 2
DirectSoundWaveData_ELP2_60::
	.incbin "sound/direct_sound_samples/gswavetable/ELP2_60.bin"

	.align 2
DirectSoundWaveData_ELP2_68::
	.incbin "sound/direct_sound_samples/gswavetable/ELP2_68.bin"

	.align 2
DirectSoundWaveData_ELP2_76::
	.incbin "sound/direct_sound_samples/gswavetable/ELP2_76.bin"

	.align 2
DirectSoundWaveData_ELP2_84::
	.incbin "sound/direct_sound_samples/gswavetable/ELP2_84.bin"

	.align 2
DirectSoundWaveData_ELP2_92::
	.incbin "sound/direct_sound_samples/gswavetable/ELP2_92.bin"

	.align 2
DirectSoundWaveData_ELP2_A0::
	.incbin "sound/direct_sound_samples/gswavetable/ELP2_A0.bin"

	.align 2
DirectSoundWaveData_ELP2_A8::
	.incbin "sound/direct_sound_samples/gswavetable/ELP2_A8.bin"

	.align 2
DirectSoundWaveData_ENGIN64::
	.incbin "sound/direct_sound_samples/gswavetable/ENGIN64.bin"

	.align 2
DirectSoundWaveData_EORG173::
	.incbin "sound/direct_sound_samples/gswavetable/EORG173.bin"

	.align 2
DirectSoundWaveData_EORG185::
	.incbin "sound/direct_sound_samples/gswavetable/EORG185.bin"

	.align 2
DirectSoundWaveData_EORG197::
	.incbin "sound/direct_sound_samples/gswavetable/EORG197.bin"

	.align 2
DirectSoundWaveData_EORG253::
	.incbin "sound/direct_sound_samples/gswavetable/EORG253.bin"

	.align 2
DirectSoundWaveData_EORG268::
	.incbin "sound/direct_sound_samples/gswavetable/EORG268.bin"

	.align 2
DirectSoundWaveData_EORG286::
	.incbin "sound/direct_sound_samples/gswavetable/EORG286.bin"

	.align 2
DirectSoundWaveData_EORG367::
	.incbin "sound/direct_sound_samples/gswavetable/EORG367.bin"

	.align 2
DirectSoundWaveData_EORG379::
	.incbin "sound/direct_sound_samples/gswavetable/EORG379.bin"

	.align 2
DirectSoundWaveData_EORG391::
	.incbin "sound/direct_sound_samples/gswavetable/EORG391.bin"

	.align 2
DirectSoundWaveData_FANTA53::
	.incbin "sound/direct_sound_samples/gswavetable/FANTA53.bin"

	.align 2
DirectSoundWaveData_FANTA81::
	.incbin "sound/direct_sound_samples/gswavetable/FANTA81.bin"

	.align 2
DirectSoundWaveData_FATSD60A::
	.incbin "sound/direct_sound_samples/gswavetable/FATSD60A.bin"

	.align 2
DirectSoundWaveData_FHORN60::
	.incbin "sound/direct_sound_samples/gswavetable/FHORN60.bin"

	.align 2
DirectSoundWaveData_FHORN72::
	.incbin "sound/direct_sound_samples/gswavetable/FHORN72.bin"

	.align 2
DirectSoundWaveData_FLUTE65A::
	.incbin "sound/direct_sound_samples/gswavetable/FLUTE65A.bin"

	.align 2
DirectSoundWaveData_FLUTE73A::
	.incbin "sound/direct_sound_samples/gswavetable/FLUTE73A.bin"

	.align 2
DirectSoundWaveData_FLUTE79A::
	.incbin "sound/direct_sound_samples/gswavetable/FLUTE79A.bin"

	.align 2
DirectSoundWaveData_FLUTE88A::
	.incbin "sound/direct_sound_samples/gswavetable/FLUTE88A.bin"

	.align 2
DirectSoundWaveData_FLUTE96A::
	.incbin "sound/direct_sound_samples/gswavetable/FLUTE96A.bin"

	.align 2
DirectSoundWaveData_FLUTEA5A::
	.incbin "sound/direct_sound_samples/gswavetable/FLUTEA5A.bin"

	.align 2
DirectSoundWaveData_FMVOX66A::
	.incbin "sound/direct_sound_samples/gswavetable/FMVOX66A.bin"

	.align 2
DirectSoundWaveData_FMVOX86A::
	.incbin "sound/direct_sound_samples/gswavetable/FMVOX86A.bin"

	.align 2
DirectSoundWaveData_FNTBL53C::
	.incbin "sound/direct_sound_samples/gswavetable/FNTBL53C.bin"

	.align 2
DirectSoundWaveData_FRTLS36A::
	.incbin "sound/direct_sound_samples/gswavetable/FRTLS36A.bin"

	.align 2
DirectSoundWaveData_FRTLS48A::
	.incbin "sound/direct_sound_samples/gswavetable/FRTLS48A.bin"

	.align 2
DirectSoundWaveData_FRTLS60A::
	.incbin "sound/direct_sound_samples/gswavetable/FRTLS60A.bin"

	.align 2
DirectSoundWaveData_GATSD60A::
	.incbin "sound/direct_sound_samples/gswavetable/GATSD60A.bin"

	.align 2
DirectSoundWaveData_GFRET69::
	.incbin "sound/direct_sound_samples/gswavetable/GFRET69.bin"

	.align 2
DirectSoundWaveData_GLKN285::
	.incbin "sound/direct_sound_samples/gswavetable/GLKN285.bin"

	.align 2
DirectSoundWaveData_GLKN385::
	.incbin "sound/direct_sound_samples/gswavetable/GLKN385.bin"

	.align 2
DirectSoundWaveData_GLKN585::
	.incbin "sound/direct_sound_samples/gswavetable/GLKN585.bin"

	.align 2
DirectSoundWaveData_GOBLN84A::
	.incbin "sound/direct_sound_samples/gswavetable/GOBLN84A.bin"

	.align 2
DirectSoundWaveData_HARMO68::
	.incbin "sound/direct_sound_samples/gswavetable/HARMO68.bin"

	.align 2
DirectSoundWaveData_HARMO76::
	.incbin "sound/direct_sound_samples/gswavetable/HARMO76.bin"

	.align 2
DirectSoundWaveData_HARMO84::
	.incbin "sound/direct_sound_samples/gswavetable/HARMO84.bin"

	.align 2
DirectSoundWaveData_HARMO92::
	.incbin "sound/direct_sound_samples/gswavetable/HARMO92.bin"

	.align 2
DirectSoundWaveData_HARMOA0::
	.incbin "sound/direct_sound_samples/gswavetable/HARMOA0.bin"

	.align 2
DirectSoundWaveData_HARMOA8::
	.incbin "sound/direct_sound_samples/gswavetable/HARMOA8.bin"

	.align 2
DirectSoundWaveData_HARP_57A::
	.incbin "sound/direct_sound_samples/gswavetable/HARP_57A.bin"

	.align 2
DirectSoundWaveData_HARP_70A::
	.incbin "sound/direct_sound_samples/gswavetable/HARP_70A.bin"

	.align 2
DirectSoundWaveData_HARP_83A::
	.incbin "sound/direct_sound_samples/gswavetable/HARP_83A.bin"

	.align 2
DirectSoundWaveData_HARP_96A::
	.incbin "sound/direct_sound_samples/gswavetable/HARP_96A.bin"

	.align 2
DirectSoundWaveData_HBNGO60::
	.incbin "sound/direct_sound_samples/gswavetable/HBNGO60.bin"

	.align 2
DirectSoundWaveData_HCLAP60::
	.incbin "sound/direct_sound_samples/gswavetable/HCLAP60.bin"

	.align 2
DirectSoundWaveData_HEART64::
	.incbin "sound/direct_sound_samples/gswavetable/HEART64.bin"

	.align 2
DirectSoundWaveData_HELI_60::
	.incbin "sound/direct_sound_samples/gswavetable/HELI_60.bin"

	.align 2
DirectSoundWaveData_HI_Q_60::
	.incbin "sound/direct_sound_samples/gswavetable/HI_Q_60.bin"

	.align 2
DirectSoundWaveData_HONKY42A::
	.incbin "sound/direct_sound_samples/gswavetable/HONKY42A.bin"

	.align 2
DirectSoundWaveData_HONKY62B::
	.incbin "sound/direct_sound_samples/gswavetable/HONKY62B.bin"

	.align 2
DirectSoundWaveData_HONKY71A::
	.incbin "sound/direct_sound_samples/gswavetable/HONKY71A.bin"

	.align 2
DirectSoundWaveData_HONKY84A::
	.incbin "sound/direct_sound_samples/gswavetable/HONKY84A.bin"

	.align 2
DirectSoundWaveData_HONKY96A::
	.incbin "sound/direct_sound_samples/gswavetable/HONKY96A.bin"

	.align 2
DirectSoundWaveData_HORSE64::
	.incbin "sound/direct_sound_samples/gswavetable/HORSE64.bin"

	.align 2
DirectSoundWaveData_HRMGT52::
	.incbin "sound/direct_sound_samples/gswavetable/HRMGT52.bin"

	.align 2
DirectSoundWaveData_HRMGT76::
	.incbin "sound/direct_sound_samples/gswavetable/HRMGT76.bin"

	.align 2
DirectSoundWaveData_HRPSI48A::
	.incbin "sound/direct_sound_samples/gswavetable/HRPSI48A.bin"

	.align 2
DirectSoundWaveData_HRPSI60A::
	.incbin "sound/direct_sound_samples/gswavetable/HRPSI60A.bin"

	.align 2
DirectSoundWaveData_HRPSI72A::
	.incbin "sound/direct_sound_samples/gswavetable/HRPSI72A.bin"

	.align 2
DirectSoundWaveData_HRPSI87A::
	.incbin "sound/direct_sound_samples/gswavetable/HRPSI87A.bin"

	.align 2
DirectSoundWaveData_ICE__60A::
	.incbin "sound/direct_sound_samples/gswavetable/ICE__60A.bin"

	.align 2
DirectSoundWaveData_ICE__84A::
	.incbin "sound/direct_sound_samples/gswavetable/ICE__84A.bin"

	.align 2
DirectSoundWaveData_JAZGT50A::
	.incbin "sound/direct_sound_samples/gswavetable/JAZGT50A.bin"

	.align 2
DirectSoundWaveData_JAZGT59A::
	.incbin "sound/direct_sound_samples/gswavetable/JAZGT59A.bin"

	.align 2
DirectSoundWaveData_JAZGT68A::
	.incbin "sound/direct_sound_samples/gswavetable/JAZGT68A.bin"

	.align 2
DirectSoundWaveData_JAZGT74A::
	.incbin "sound/direct_sound_samples/gswavetable/JAZGT74A.bin"

	.align 2
DirectSoundWaveData_JAZGT84A::
	.incbin "sound/direct_sound_samples/gswavetable/JAZGT84A.bin"

	.align 2
DirectSoundWaveData_JAZGT93A::
	.incbin "sound/direct_sound_samples/gswavetable/JAZGT93A.bin"

	.align 2
DirectSoundWaveData_JAZGTA1A::
	.incbin "sound/direct_sound_samples/gswavetable/JAZGTA1A.bin"

	.align 2
DirectSoundWaveData_JBELL60::
	.incbin "sound/direct_sound_samples/gswavetable/JBELL60.bin"

	.align 2
DirectSoundWaveData_KEY__60::
	.incbin "sound/direct_sound_samples/gswavetable/KEY__60.bin"

	.align 2
DirectSoundWaveData_KICK264::
	.incbin "sound/direct_sound_samples/gswavetable/KICK264.bin"

	.align 2
DirectSoundWaveData_KLMBA70::
	.incbin "sound/direct_sound_samples/gswavetable/KLMBA70.bin"

	.align 2
DirectSoundWaveData_KOTO_57::
	.incbin "sound/direct_sound_samples/gswavetable/KOTO_57.bin"

	.align 2
DirectSoundWaveData_KOTO_80::
	.incbin "sound/direct_sound_samples/gswavetable/KOTO_80.bin"

	.align 2
DirectSoundWaveData_KOTO_A2A::
	.incbin "sound/direct_sound_samples/gswavetable/KOTO_A2A.bin"

	.align 2
DirectSoundWaveData_LASER64A::
	.incbin "sound/direct_sound_samples/gswavetable/LASER64A.bin"

	.align 2
DirectSoundWaveData_LAUGH59A::
	.incbin "sound/direct_sound_samples/gswavetable/LAUGH59A.bin"

	.align 2
DirectSoundWaveData_LBNGO60::
	.incbin "sound/direct_sound_samples/gswavetable/LBNGO60.bin"

	.align 2
DirectSoundWaveData_LGUIR60::
	.incbin "sound/direct_sound_samples/gswavetable/LGUIR60.bin"

	.align 2
DirectSoundWaveData_LWHSL60A::
	.incbin "sound/direct_sound_samples/gswavetable/LWHSL60A.bin"

	.align 2
DirectSoundWaveData_MARCS60::
	.incbin "sound/direct_sound_samples/gswavetable/MARCS60.bin"

	.align 2
DirectSoundWaveData_MCNGA60::
	.incbin "sound/direct_sound_samples/gswavetable/MCNGA60.bin"

	.align 2
DirectSoundWaveData_MCUIC60::
	.incbin "sound/direct_sound_samples/gswavetable/MCUIC60.bin"

	.align 2
DirectSoundWaveData_METRO60::
	.incbin "sound/direct_sound_samples/gswavetable/METRO60.bin"

	.align 2
DirectSoundWaveData_MGSQR45::
	.incbin "sound/direct_sound_samples/gswavetable/MGSQR45.bin"

	.align 2
DirectSoundWaveData_MGSQR57::
	.incbin "sound/direct_sound_samples/gswavetable/MGSQR57.bin"

	.align 2
DirectSoundWaveData_MGSQR69::
	.incbin "sound/direct_sound_samples/gswavetable/MGSQR69.bin"

	.align 2
DirectSoundWaveData_MGSQR81::
	.incbin "sound/direct_sound_samples/gswavetable/MGSQR81.bin"

	.align 2
DirectSoundWaveData_MGSQR93::
	.incbin "sound/direct_sound_samples/gswavetable/MGSQR93.bin"

	.align 2
DirectSoundWaveData_MMBAS40::
	.incbin "sound/direct_sound_samples/gswavetable/MMBAS40.bin"

	.align 2
DirectSoundWaveData_MMBAS43::
	.incbin "sound/direct_sound_samples/gswavetable/MMBAS43.bin"

	.align 2
DirectSoundWaveData_MMBAS62::
	.incbin "sound/direct_sound_samples/gswavetable/MMBAS62.bin"

	.align 2
DirectSoundWaveData_MONDO60::
	.incbin "sound/direct_sound_samples/gswavetable/MONDO60.bin"

	.align 2
DirectSoundWaveData_MRMBA50::
	.incbin "sound/direct_sound_samples/gswavetable/MRMBA50.bin"

	.align 2
DirectSoundWaveData_MRMBA62::
	.incbin "sound/direct_sound_samples/gswavetable/MRMBA62.bin"

	.align 2
DirectSoundWaveData_MRMBA90::
	.incbin "sound/direct_sound_samples/gswavetable/MRMBA90.bin"

	.align 2
DirectSoundWaveData_MUTGT43::
	.incbin "sound/direct_sound_samples/gswavetable/MUTGT43.bin"

	.align 2
DirectSoundWaveData_MUTGT64::
	.incbin "sound/direct_sound_samples/gswavetable/MUTGT64.bin"

	.align 2
DirectSoundWaveData_MUTGT81::
	.incbin "sound/direct_sound_samples/gswavetable/MUTGT81.bin"

	.align 2
DirectSoundWaveData_MUTTP64B::
	.incbin "sound/direct_sound_samples/gswavetable/MUTTP64B.bin"

	.align 2
DirectSoundWaveData_MUTTP73B::
	.incbin "sound/direct_sound_samples/gswavetable/MUTTP73B.bin"

	.align 2
DirectSoundWaveData_MUTTP79B::
	.incbin "sound/direct_sound_samples/gswavetable/MUTTP79B.bin"

	.align 2
DirectSoundWaveData_MUTTP86B::
	.incbin "sound/direct_sound_samples/gswavetable/MUTTP86B.bin"

	.align 2
DirectSoundWaveData_M_BOX82::
	.incbin "sound/direct_sound_samples/gswavetable/M_BOX82.bin"

	.align 2
DirectSoundWaveData_M_GUN64::
	.incbin "sound/direct_sound_samples/gswavetable/M_GUN64.bin"

	.align 2
DirectSoundWaveData_NYLON48A::
	.incbin "sound/direct_sound_samples/gswavetable/NYLON48A.bin"

	.align 2
DirectSoundWaveData_NYLON57A::
	.incbin "sound/direct_sound_samples/gswavetable/NYLON57A.bin"

	.align 2
DirectSoundWaveData_NYLON70A::
	.incbin "sound/direct_sound_samples/gswavetable/NYLON70A.bin"

	.align 2
DirectSoundWaveData_NYLON79A::
	.incbin "sound/direct_sound_samples/gswavetable/NYLON79A.bin"

	.align 2
DirectSoundWaveData_NYLON88A::
	.incbin "sound/direct_sound_samples/gswavetable/NYLON88A.bin"

	.align 2
DirectSoundWaveData_NYLON97A::
	.incbin "sound/direct_sound_samples/gswavetable/NYLON97A.bin"

	.align 2
DirectSoundWaveData_NYLONA5A::
	.incbin "sound/direct_sound_samples/gswavetable/NYLONA5A.bin"

	.align 2
DirectSoundWaveData_OBOE_61A::
	.incbin "sound/direct_sound_samples/gswavetable/OBOE_61A.bin"

	.align 2
DirectSoundWaveData_OBOE_69A::
	.incbin "sound/direct_sound_samples/gswavetable/OBOE_69A.bin"

	.align 2
DirectSoundWaveData_OBOE_77A::
	.incbin "sound/direct_sound_samples/gswavetable/OBOE_77A.bin"

	.align 2
DirectSoundWaveData_OBOE_81::
	.incbin "sound/direct_sound_samples/gswavetable/OBOE_81.bin"

	.align 2
DirectSoundWaveData_OBOE_85A::
	.incbin "sound/direct_sound_samples/gswavetable/OBOE_85A.bin"

	.align 2
DirectSoundWaveData_OCARI72A::
	.incbin "sound/direct_sound_samples/gswavetable/OCARI72A.bin"

	.align 2
DirectSoundWaveData_OCARI84A::
	.incbin "sound/direct_sound_samples/gswavetable/OCARI84A.bin"

	.align 2
DirectSoundWaveData_OCARI96A::
	.incbin "sound/direct_sound_samples/gswavetable/OCARI96A.bin"

	.align 2
DirectSoundWaveData_OCNGA60::
	.incbin "sound/direct_sound_samples/gswavetable/OCNGA60.bin"

	.align 2
DirectSoundWaveData_OCUIC60::
	.incbin "sound/direct_sound_samples/gswavetable/OCUIC60.bin"

	.align 2
DirectSoundWaveData_OHH__60B::
	.incbin "sound/direct_sound_samples/gswavetable/OHH__60B.bin"

	.align 2
DirectSoundWaveData_OVDRV44::
	.incbin "sound/direct_sound_samples/gswavetable/OVDRV44.bin"

	.align 2
DirectSoundWaveData_OVDRV49::
	.incbin "sound/direct_sound_samples/gswavetable/OVDRV49.bin"

	.align 2
DirectSoundWaveData_OVDRV60::
	.incbin "sound/direct_sound_samples/gswavetable/OVDRV60.bin"

	.align 2
DirectSoundWaveData_OVDRV60A::
	.incbin "sound/direct_sound_samples/gswavetable/OVDRV60A.bin"

	.align 2
DirectSoundWaveData_OVDRV70::
	.incbin "sound/direct_sound_samples/gswavetable/OVDRV70.bin"

	.align 2
DirectSoundWaveData_OVDRV73::
	.incbin "sound/direct_sound_samples/gswavetable/OVDRV73.bin"

	.align 2
DirectSoundWaveData_OVDRV77::
	.incbin "sound/direct_sound_samples/gswavetable/OVDRV77.bin"

	.align 2
DirectSoundWaveData_OVDRV89::
	.incbin "sound/direct_sound_samples/gswavetable/OVDRV89.bin"

	.align 2
DirectSoundWaveData_OVDRV96::
	.incbin "sound/direct_sound_samples/gswavetable/OVDRV96.bin"

	.align 2
DirectSoundWaveData_OVDRVA6::
	.incbin "sound/direct_sound_samples/gswavetable/OVDRVA6.bin"

	.align 2
DirectSoundWaveData_O_HIT68::
	.incbin "sound/direct_sound_samples/gswavetable/O_HIT68.bin"

	.align 2
DirectSoundWaveData_PANNS84::
	.incbin "sound/direct_sound_samples/gswavetable/PANNS84.bin"

	.align 2
DirectSoundWaveData_PANNS96::
	.incbin "sound/direct_sound_samples/gswavetable/PANNS96.bin"

	.align 2
DirectSoundWaveData_PCKBS30A::
	.incbin "sound/direct_sound_samples/gswavetable/PCKBS30A.bin"

	.align 2
DirectSoundWaveData_PCKBS40A::
	.incbin "sound/direct_sound_samples/gswavetable/PCKBS40A.bin"

	.align 2
DirectSoundWaveData_PCKBS50A::
	.incbin "sound/direct_sound_samples/gswavetable/PCKBS50A.bin"

	.align 2
DirectSoundWaveData_PIANO36::
	.incbin "sound/direct_sound_samples/gswavetable/PIANO36.bin"

	.align 2
DirectSoundWaveData_PIANO41::
	.incbin "sound/direct_sound_samples/gswavetable/PIANO41.bin"

	.align 2
DirectSoundWaveData_PIANO48::
	.incbin "sound/direct_sound_samples/gswavetable/PIANO48.bin"

	.align 2
DirectSoundWaveData_PIANO56::
	.incbin "sound/direct_sound_samples/gswavetable/PIANO56.bin"

	.align 2
DirectSoundWaveData_PIANO64::
	.incbin "sound/direct_sound_samples/gswavetable/PIANO64.bin"

	.align 2
DirectSoundWaveData_PIANO73::
	.incbin "sound/direct_sound_samples/gswavetable/PIANO73.bin"

	.align 2
DirectSoundWaveData_PIANO78::
	.incbin "sound/direct_sound_samples/gswavetable/PIANO78.bin"

	.align 2
DirectSoundWaveData_PIANO84::
	.incbin "sound/direct_sound_samples/gswavetable/PIANO84.bin"

	.align 2
DirectSoundWaveData_PIANO92::
	.incbin "sound/direct_sound_samples/gswavetable/PIANO92.bin"

	.align 2
DirectSoundWaveData_PIANOA3::
	.incbin "sound/direct_sound_samples/gswavetable/PIANOA3.bin"

	.align 2
DirectSoundWaveData_PICLO79::
	.incbin "sound/direct_sound_samples/gswavetable/PICLO79.bin"

	.align 2
DirectSoundWaveData_PICLO84::
	.incbin "sound/direct_sound_samples/gswavetable/PICLO84.bin"

	.align 2
DirectSoundWaveData_PICLO98::
	.incbin "sound/direct_sound_samples/gswavetable/PICLO98.bin"

	.align 2
DirectSoundWaveData_PISTL60::
	.incbin "sound/direct_sound_samples/gswavetable/PISTL60.bin"

	.align 2
DirectSoundWaveData_PIZZH84::
	.incbin "sound/direct_sound_samples/gswavetable/PIZZH84.bin"

	.align 2
DirectSoundWaveData_PIZZ_71::
	.incbin "sound/direct_sound_samples/gswavetable/PIZZ_71.bin"

	.align 2
DirectSoundWaveData_PNFLT72::
	.incbin "sound/direct_sound_samples/gswavetable/PNFLT72.bin"

	.align 2
DirectSoundWaveData_POLY_48A::
	.incbin "sound/direct_sound_samples/gswavetable/POLY_48A.bin"

	.align 2
DirectSoundWaveData_POLY_60A::
	.incbin "sound/direct_sound_samples/gswavetable/POLY_60A.bin"

	.align 2
DirectSoundWaveData_POLY_72A::
	.incbin "sound/direct_sound_samples/gswavetable/POLY_72A.bin"

	.align 2
DirectSoundWaveData_POLY_84A::
	.incbin "sound/direct_sound_samples/gswavetable/POLY_84A.bin"

	.align 2
DirectSoundWaveData_POLY_96A::
	.incbin "sound/direct_sound_samples/gswavetable/POLY_96A.bin"

	.align 2
DirectSoundWaveData_POPVX64A::
	.incbin "sound/direct_sound_samples/gswavetable/POPVX64A.bin"

	.align 2
DirectSoundWaveData_POPVX71A::
	.incbin "sound/direct_sound_samples/gswavetable/POPVX71A.bin"

	.align 2
DirectSoundWaveData_POPVX74A::
	.incbin "sound/direct_sound_samples/gswavetable/POPVX74A.bin"

	.align 2
DirectSoundWaveData_PUNCH64::
	.incbin "sound/direct_sound_samples/gswavetable/PUNCH64.bin"

	.align 2
DirectSoundWaveData_RDBEL64B::
	.incbin "sound/direct_sound_samples/gswavetable/RDBEL64B.bin"

	.align 2
DirectSoundWaveData_RDCYM60B::
	.incbin "sound/direct_sound_samples/gswavetable/RDCYM60B.bin"

	.align 2
DirectSoundWaveData_RECDR66A::
	.incbin "sound/direct_sound_samples/gswavetable/RECDR66A.bin"

	.align 2
DirectSoundWaveData_RECDR75A::
	.incbin "sound/direct_sound_samples/gswavetable/RECDR75A.bin"

	.align 2
DirectSoundWaveData_RECDR83A::
	.incbin "sound/direct_sound_samples/gswavetable/RECDR83A.bin"

	.align 2
DirectSoundWaveData_RECDR93A::
	.incbin "sound/direct_sound_samples/gswavetable/RECDR93A.bin"

	.align 2
DirectSoundWaveData_RECDRA3A::
	.incbin "sound/direct_sound_samples/gswavetable/RECDRA3A.bin"

	.align 2
DirectSoundWaveData_R_ORG53::
	.incbin "sound/direct_sound_samples/gswavetable/R_ORG53.bin"

	.align 2
DirectSoundWaveData_R_ORG72::
	.incbin "sound/direct_sound_samples/gswavetable/R_ORG72.bin"

	.align 2
DirectSoundWaveData_R_ORG88::
	.incbin "sound/direct_sound_samples/gswavetable/R_ORG88.bin"

	.align 2
DirectSoundWaveData_SANTR74::
	.incbin "sound/direct_sound_samples/gswavetable/SANTR74.bin"

	.align 2
DirectSoundWaveData_SAW0_48::
	.incbin "sound/direct_sound_samples/gswavetable/SAW0_48.bin"

	.align 2
DirectSoundWaveData_SAW0_60::
	.incbin "sound/direct_sound_samples/gswavetable/SAW0_60.bin"

	.align 2
DirectSoundWaveData_SAW0_72::
	.incbin "sound/direct_sound_samples/gswavetable/SAW0_72.bin"

	.align 2
DirectSoundWaveData_SAW__40::
	.incbin "sound/direct_sound_samples/gswavetable/SAW__40.bin"

	.align 2
DirectSoundWaveData_SAW__52::
	.incbin "sound/direct_sound_samples/gswavetable/SAW__52.bin"

	.align 2
DirectSoundWaveData_SAW__64::
	.incbin "sound/direct_sound_samples/gswavetable/SAW__64.bin"

	.align 2
DirectSoundWaveData_SAW__76::
	.incbin "sound/direct_sound_samples/gswavetable/SAW__76.bin"

	.align 2
DirectSoundWaveData_SAW__88::
	.incbin "sound/direct_sound_samples/gswavetable/SAW__88.bin"

	.align 2
DirectSoundWaveData_SAW__A0A::
	.incbin "sound/direct_sound_samples/gswavetable/SAW__A0A.bin"

	.align 2
DirectSoundWaveData_SAW__A7A::
	.incbin "sound/direct_sound_samples/gswavetable/SAW__A7A.bin"

	.align 2
DirectSoundWaveData_SAW__B2A::
	.incbin "sound/direct_sound_samples/gswavetable/SAW__B2A.bin"

	.align 2
DirectSoundWaveData_SAW__B9B::
	.incbin "sound/direct_sound_samples/gswavetable/SAW__B9B.bin"

	.align 2
DirectSoundWaveData_SBRS148A::
	.incbin "sound/direct_sound_samples/gswavetable/SBRS148A.bin"

	.align 2
DirectSoundWaveData_SBRS160A::
	.incbin "sound/direct_sound_samples/gswavetable/SBRS160A.bin"

	.align 2
DirectSoundWaveData_SBRS172A::
	.incbin "sound/direct_sound_samples/gswavetable/SBRS172A.bin"

	.align 2
DirectSoundWaveData_SBRS184A::
	.incbin "sound/direct_sound_samples/gswavetable/SBRS184A.bin"

	.align 2
DirectSoundWaveData_SBRS196A::
	.incbin "sound/direct_sound_samples/gswavetable/SBRS196A.bin"

	.align 2
DirectSoundWaveData_SBRS243::
	.incbin "sound/direct_sound_samples/gswavetable/SBRS243.bin"

	.align 2
DirectSoundWaveData_SBRS255::
	.incbin "sound/direct_sound_samples/gswavetable/SBRS255.bin"

	.align 2
DirectSoundWaveData_SBRS272::
	.incbin "sound/direct_sound_samples/gswavetable/SBRS272.bin"

	.align 2
DirectSoundWaveData_SBRS296::
	.incbin "sound/direct_sound_samples/gswavetable/SBRS296.bin"

	.align 2
DirectSoundWaveData_SCRCH64::
	.incbin "sound/direct_sound_samples/gswavetable/SCRCH64.bin"

	.align 2
DirectSoundWaveData_SCREM64A::
	.incbin "sound/direct_sound_samples/gswavetable/SCREM64A.bin"

	.align 2
DirectSoundWaveData_SDOOR64::
	.incbin "sound/direct_sound_samples/gswavetable/SDOOR64.bin"

	.align 2
DirectSoundWaveData_SEA__60::
	.incbin "sound/direct_sound_samples/gswavetable/SEA__60.bin"

	.align 2
DirectSoundWaveData_SGUIR60::
	.incbin "sound/direct_sound_samples/gswavetable/SGUIR60.bin"

	.align 2
DirectSoundWaveData_SHAKU63::
	.incbin "sound/direct_sound_samples/gswavetable/SHAKU63.bin"

	.align 2
DirectSoundWaveData_SHAKU70::
	.incbin "sound/direct_sound_samples/gswavetable/SHAKU70.bin"

	.align 2
DirectSoundWaveData_SHAKU78::
	.incbin "sound/direct_sound_samples/gswavetable/SHAKU78.bin"

	.align 2
DirectSoundWaveData_SHAMI53::
	.incbin "sound/direct_sound_samples/gswavetable/SHAMI53.bin"

	.align 2
DirectSoundWaveData_SHAMI65::
	.incbin "sound/direct_sound_samples/gswavetable/SHAMI65.bin"

	.align 2
DirectSoundWaveData_SHAMI77::
	.incbin "sound/direct_sound_samples/gswavetable/SHAMI77.bin"

	.align 2
DirectSoundWaveData_SHAMI89::
	.incbin "sound/direct_sound_samples/gswavetable/SHAMI89.bin"

	.align 2
DirectSoundWaveData_SIDE_60::
	.incbin "sound/direct_sound_samples/gswavetable/SIDE_60.bin"

	.align 2
DirectSoundWaveData_SINE_52::
	.incbin "sound/direct_sound_samples/gswavetable/SINE_52.bin"

	.align 2
DirectSoundWaveData_SINE_64::
	.incbin "sound/direct_sound_samples/gswavetable/SINE_64.bin"

	.align 2
DirectSoundWaveData_SINE_76::
	.incbin "sound/direct_sound_samples/gswavetable/SINE_76.bin"

	.align 2
DirectSoundWaveData_SINE_88::
	.incbin "sound/direct_sound_samples/gswavetable/SINE_88.bin"

	.align 2
DirectSoundWaveData_SINE_A0A::
	.incbin "sound/direct_sound_samples/gswavetable/SINE_A0A.bin"

	.align 2
DirectSoundWaveData_SINE_B2A::
	.incbin "sound/direct_sound_samples/gswavetable/SINE_B2A.bin"

	.align 2
DirectSoundWaveData_SINE_B9::
	.incbin "sound/direct_sound_samples/gswavetable/SINE_B9.bin"

	.align 2
DirectSoundWaveData_SIREN64::
	.incbin "sound/direct_sound_samples/gswavetable/SIREN64.bin"

	.align 2
DirectSoundWaveData_SITAR60::
	.incbin "sound/direct_sound_samples/gswavetable/SITAR60.bin"

	.align 2
DirectSoundWaveData_SITAR76::
	.incbin "sound/direct_sound_samples/gswavetable/SITAR76.bin"

	.align 2
DirectSoundWaveData_SITAR95::
	.incbin "sound/direct_sound_samples/gswavetable/SITAR95.bin"

	.align 2
DirectSoundWaveData_SLAP_60::
	.incbin "sound/direct_sound_samples/gswavetable/SLAP_60.bin"

	.align 2
DirectSoundWaveData_SLPBS31::
	.incbin "sound/direct_sound_samples/gswavetable/SLPBS31.bin"

	.align 2
DirectSoundWaveData_SLPBS43::
	.incbin "sound/direct_sound_samples/gswavetable/SLPBS43.bin"

	.align 2
DirectSoundWaveData_SLPBS84::
	.incbin "sound/direct_sound_samples/gswavetable/SLPBS84.bin"

	.align 2
DirectSoundWaveData_SLPMT52A::
	.incbin "sound/direct_sound_samples/gswavetable/SLPMT52A.bin"

	.align 2
DirectSoundWaveData_SOLKK60A::
	.incbin "sound/direct_sound_samples/gswavetable/SOLKK60A.bin"

	.align 2
DirectSoundWaveData_SOUND60::
	.incbin "sound/direct_sound_samples/gswavetable/SOUND60.bin"

	.align 2
DirectSoundWaveData_SOUND84::
	.incbin "sound/direct_sound_samples/gswavetable/SOUND84.bin"

	.align 2
DirectSoundWaveData_SPACE79::
	.incbin "sound/direct_sound_samples/gswavetable/SPACE79.bin"

	.align 2
DirectSoundWaveData_SPULL60::
	.incbin "sound/direct_sound_samples/gswavetable/SPULL60.bin"

	.align 2
DirectSoundWaveData_SPUSH60::
	.incbin "sound/direct_sound_samples/gswavetable/SPUSH60.bin"

	.align 2
DirectSoundWaveData_SQUAR41::
	.incbin "sound/direct_sound_samples/gswavetable/SQUAR41.bin"

	.align 2
DirectSoundWaveData_SQUAR48::
	.incbin "sound/direct_sound_samples/gswavetable/SQUAR48.bin"

	.align 2
DirectSoundWaveData_SQUAR60::
	.incbin "sound/direct_sound_samples/gswavetable/SQUAR60.bin"

	.align 2
DirectSoundWaveData_SQUAR67::
	.incbin "sound/direct_sound_samples/gswavetable/SQUAR67.bin"

	.align 2
DirectSoundWaveData_SQUAR79::
	.incbin "sound/direct_sound_samples/gswavetable/SQUAR79.bin"

	.align 2
DirectSoundWaveData_SQUAR96::
	.incbin "sound/direct_sound_samples/gswavetable/SQUAR96.bin"

	.align 2
DirectSoundWaveData_SSTR148::
	.incbin "sound/direct_sound_samples/gswavetable/SSTR148.bin"

	.align 2
DirectSoundWaveData_SSTR162A::
	.incbin "sound/direct_sound_samples/gswavetable/SSTR162A.bin"

	.align 2
DirectSoundWaveData_SSTR186A::
	.incbin "sound/direct_sound_samples/gswavetable/SSTR186A.bin"

	.align 2
DirectSoundWaveData_SSTR367::
	.incbin "sound/direct_sound_samples/gswavetable/SSTR367.bin"

	.align 2
DirectSoundWaveData_SSTR382::
	.incbin "sound/direct_sound_samples/gswavetable/SSTR382.bin"

	.align 2
DirectSoundWaveData_STAR_60A::
	.incbin "sound/direct_sound_samples/gswavetable/STAR_60A.bin"

	.align 2
DirectSoundWaveData_STAR_84A::
	.incbin "sound/direct_sound_samples/gswavetable/STAR_84A.bin"

	.align 2
DirectSoundWaveData_STEPS64::
	.incbin "sound/direct_sound_samples/gswavetable/STEPS64.bin"

	.align 2
DirectSoundWaveData_STICK64::
	.incbin "sound/direct_sound_samples/gswavetable/STICK64.bin"

	.align 2
DirectSoundWaveData_STLDR72::
	.incbin "sound/direct_sound_samples/gswavetable/STLDR72.bin"

	.align 2
DirectSoundWaveData_STLGT41B::
	.incbin "sound/direct_sound_samples/gswavetable/STLGT41B.bin"

	.align 2
DirectSoundWaveData_STLGT49B::
	.incbin "sound/direct_sound_samples/gswavetable/STLGT49B.bin"

	.align 2
DirectSoundWaveData_STLGT57B::
	.incbin "sound/direct_sound_samples/gswavetable/STLGT57B.bin"

	.align 2
DirectSoundWaveData_STLGT65B::
	.incbin "sound/direct_sound_samples/gswavetable/STLGT65B.bin"

	.align 2
DirectSoundWaveData_STLGT74B::
	.incbin "sound/direct_sound_samples/gswavetable/STLGT74B.bin"

	.align 2
DirectSoundWaveData_STLGT84B::
	.incbin "sound/direct_sound_samples/gswavetable/STLGT84B.bin"

	.align 2
DirectSoundWaveData_STREM67B::
	.incbin "sound/direct_sound_samples/gswavetable/STREM67B.bin"

	.align 2
DirectSoundWaveData_STRNG52B::
	.incbin "sound/direct_sound_samples/gswavetable/STRNG52B.bin"

	.align 2
DirectSoundWaveData_STRNG71B::
	.incbin "sound/direct_sound_samples/gswavetable/STRNG71B.bin"

	.align 2
DirectSoundWaveData_STRNG88B::
	.incbin "sound/direct_sound_samples/gswavetable/STRNG88B.bin"

	.align 2
DirectSoundWaveData_STSHP64::
	.incbin "sound/direct_sound_samples/gswavetable/STSHP64.bin"

	.align 2
DirectSoundWaveData_SURDO60::
	.incbin "sound/direct_sound_samples/gswavetable/SURDO60.bin"

	.align 2
DirectSoundWaveData_SWHSL60A::
	.incbin "sound/direct_sound_samples/gswavetable/SWHSL60A.bin"

	.align 2
DirectSoundWaveData_SYBS133::
	.incbin "sound/direct_sound_samples/gswavetable/SYBS133.bin"

	.align 2
DirectSoundWaveData_SYBS148A::
	.incbin "sound/direct_sound_samples/gswavetable/SYBS148A.bin"

	.align 2
DirectSoundWaveData_SYBS172A::
	.incbin "sound/direct_sound_samples/gswavetable/SYBS172A.bin"

	.align 2
DirectSoundWaveData_SYBS196A::
	.incbin "sound/direct_sound_samples/gswavetable/SYBS196A.bin"

	.align 2
DirectSoundWaveData_SYBS233::
	.incbin "sound/direct_sound_samples/gswavetable/SYBS233.bin"

	.align 2
DirectSoundWaveData_SYBS248A::
	.incbin "sound/direct_sound_samples/gswavetable/SYBS248A.bin"

	.align 2
DirectSoundWaveData_SYBS272A::
	.incbin "sound/direct_sound_samples/gswavetable/SYBS272A.bin"

	.align 2
DirectSoundWaveData_SYBS336A::
	.incbin "sound/direct_sound_samples/gswavetable/SYBS336A.bin"

	.align 2
DirectSoundWaveData_SYBS429A::
	.incbin "sound/direct_sound_samples/gswavetable/SYBS429A.bin"

	.align 2
DirectSoundWaveData_SYNCL55::
	.incbin "sound/direct_sound_samples/gswavetable/SYNCL55.bin"

	.align 2
DirectSoundWaveData_SYNCL64::
	.incbin "sound/direct_sound_samples/gswavetable/SYNCL64.bin"

	.align 2
DirectSoundWaveData_SYNCL70::
	.incbin "sound/direct_sound_samples/gswavetable/SYNCL70.bin"

	.align 2
DirectSoundWaveData_SYNCL75::
	.incbin "sound/direct_sound_samples/gswavetable/SYNCL75.bin"

	.align 2
DirectSoundWaveData_SYNCL87::
	.incbin "sound/direct_sound_samples/gswavetable/SYNCL87.bin"

	.align 2
DirectSoundWaveData_SYNDR56::
	.incbin "sound/direct_sound_samples/gswavetable/SYNDR56.bin"

	.align 2
DirectSoundWaveData_SYNVX70::
	.incbin "sound/direct_sound_samples/gswavetable/SYNVX70.bin"

	.align 2
DirectSoundWaveData_SYNVXA6A::
	.incbin "sound/direct_sound_samples/gswavetable/SYNVXA6A.bin"

	.align 2
DirectSoundWaveData_S_SAX70::
	.incbin "sound/direct_sound_samples/gswavetable/S_SAX70.bin"

	.align 2
DirectSoundWaveData_S_SAX76::
	.incbin "sound/direct_sound_samples/gswavetable/S_SAX76.bin"

	.align 2
DirectSoundWaveData_S_SAX82::
	.incbin "sound/direct_sound_samples/gswavetable/S_SAX82.bin"

	.align 2
DirectSoundWaveData_S_SAX88::
	.incbin "sound/direct_sound_samples/gswavetable/S_SAX88.bin"

	.align 2
DirectSoundWaveData_S_SAX95::
	.incbin "sound/direct_sound_samples/gswavetable/S_SAX95.bin"

	.align 2
DirectSoundWaveData_S_SAXA2::
	.incbin "sound/direct_sound_samples/gswavetable/S_SAXA2.bin"

	.align 2
DirectSoundWaveData_S_SAXA8::
	.incbin "sound/direct_sound_samples/gswavetable/S_SAXA8.bin"

	.align 2
DirectSoundWaveData_TAMBO60::
	.incbin "sound/direct_sound_samples/gswavetable/TAMBO60.bin"

	.align 2
DirectSoundWaveData_TELE260::
	.incbin "sound/direct_sound_samples/gswavetable/TELE260.bin"

	.align 2
DirectSoundWaveData_TELE_60::
	.incbin "sound/direct_sound_samples/gswavetable/TELE_60.bin"

	.align 2
DirectSoundWaveData_THUND64::
	.incbin "sound/direct_sound_samples/gswavetable/THUND64.bin"

	.align 2
DirectSoundWaveData_TIMBL60::
	.incbin "sound/direct_sound_samples/gswavetable/TIMBL60.bin"

	.align 2
DirectSoundWaveData_TKOTO67::
	.incbin "sound/direct_sound_samples/gswavetable/TKOTO67.bin"

	.align 2
DirectSoundWaveData_TKOTO79::
	.incbin "sound/direct_sound_samples/gswavetable/TKOTO79.bin"

	.align 2
DirectSoundWaveData_TMPNI47::
	.incbin "sound/direct_sound_samples/gswavetable/TMPNI47.bin"

	.align 2
DirectSoundWaveData_TNKBLA5::
	.incbin "sound/direct_sound_samples/gswavetable/TNKBLA5.bin"

	.align 2
DirectSoundWaveData_TOM__60::
	.incbin "sound/direct_sound_samples/gswavetable/TOM__60.bin"

	.align 2
DirectSoundWaveData_TRAIN64::
	.incbin "sound/direct_sound_samples/gswavetable/TRAIN64.bin"

	.align 2
DirectSoundWaveData_TRI__60::
	.incbin "sound/direct_sound_samples/gswavetable/TRI__60.bin"

	.align 2
DirectSoundWaveData_TRMBN40A::
	.incbin "sound/direct_sound_samples/gswavetable/TRMBN40A.bin"

	.align 2
DirectSoundWaveData_TRMBN48A::
	.incbin "sound/direct_sound_samples/gswavetable/TRMBN48A.bin"

	.align 2
DirectSoundWaveData_TRMBN55A::
	.incbin "sound/direct_sound_samples/gswavetable/TRMBN55A.bin"

	.align 2
DirectSoundWaveData_TRMBN62A::
	.incbin "sound/direct_sound_samples/gswavetable/TRMBN62A.bin"

	.align 2
DirectSoundWaveData_TRMBN68A::
	.incbin "sound/direct_sound_samples/gswavetable/TRMBN68A.bin"

	.align 2
DirectSoundWaveData_TRMBN77A::
	.incbin "sound/direct_sound_samples/gswavetable/TRMBN77A.bin"

	.align 2
DirectSoundWaveData_TRMBN86A::
	.incbin "sound/direct_sound_samples/gswavetable/TRMBN86A.bin"

	.align 2
DirectSoundWaveData_TRMBN93A::
	.incbin "sound/direct_sound_samples/gswavetable/TRMBN93A.bin"

	.align 2
DirectSoundWaveData_TRMPT65::
	.incbin "sound/direct_sound_samples/gswavetable/TRMPT65.bin"

	.align 2
DirectSoundWaveData_TRMPT73::
	.incbin "sound/direct_sound_samples/gswavetable/TRMPT73.bin"

	.align 2
DirectSoundWaveData_TRMPT81::
	.incbin "sound/direct_sound_samples/gswavetable/TRMPT81.bin"

	.align 2
DirectSoundWaveData_TRMPT86::
	.incbin "sound/direct_sound_samples/gswavetable/TRMPT86.bin"

	.align 2
DirectSoundWaveData_TRMPT92::
	.incbin "sound/direct_sound_samples/gswavetable/TRMPT92.bin"

	.align 2
DirectSoundWaveData_TRMPTA1::
	.incbin "sound/direct_sound_samples/gswavetable/TRMPTA1.bin"

	.align 2
DirectSoundWaveData_TRMPTB1A::
	.incbin "sound/direct_sound_samples/gswavetable/TRMPTB1A.bin"

	.align 2
DirectSoundWaveData_TUBA_34::
	.incbin "sound/direct_sound_samples/gswavetable/TUBA_34.bin"

	.align 2
DirectSoundWaveData_TUBA_45::
	.incbin "sound/direct_sound_samples/gswavetable/TUBA_45.bin"

	.align 2
DirectSoundWaveData_TUBLR84::
	.incbin "sound/direct_sound_samples/gswavetable/TUBLR84.bin"

	.align 2
DirectSoundWaveData_T_SAX46::
	.incbin "sound/direct_sound_samples/gswavetable/T_SAX46.bin"

	.align 2
DirectSoundWaveData_T_SAX57::
	.incbin "sound/direct_sound_samples/gswavetable/T_SAX57.bin"

	.align 2
DirectSoundWaveData_T_SAX63::
	.incbin "sound/direct_sound_samples/gswavetable/T_SAX63.bin"

	.align 2
DirectSoundWaveData_T_SAX68::
	.incbin "sound/direct_sound_samples/gswavetable/T_SAX68.bin"

	.align 2
DirectSoundWaveData_T_SAX74::
	.incbin "sound/direct_sound_samples/gswavetable/T_SAX74.bin"

	.align 2
DirectSoundWaveData_T_SAX81::
	.incbin "sound/direct_sound_samples/gswavetable/T_SAX81.bin"

	.align 2
DirectSoundWaveData_T_SAX89::
	.incbin "sound/direct_sound_samples/gswavetable/T_SAX89.bin"

	.align 2
DirectSoundWaveData_T_SAX97::
	.incbin "sound/direct_sound_samples/gswavetable/T_SAX97.bin"

	.align 2
DirectSoundWaveData_T_SAXA8::
	.incbin "sound/direct_sound_samples/gswavetable/T_SAXA8.bin"

	.align 2
DirectSoundWaveData_T_SNR60A::
	.incbin "sound/direct_sound_samples/gswavetable/T_SNR60A.bin"

	.align 2
DirectSoundWaveData_UPCUT60::
	.incbin "sound/direct_sound_samples/gswavetable/UPCUT60.bin"

	.align 2
DirectSoundWaveData_VBSLP64::
	.incbin "sound/direct_sound_samples/gswavetable/VBSLP64.bin"

	.align 2
DirectSoundWaveData_VIBE_52A::
	.incbin "sound/direct_sound_samples/gswavetable/VIBE_52A.bin"

	.align 2
DirectSoundWaveData_VIBE_64A::
	.incbin "sound/direct_sound_samples/gswavetable/VIBE_64A.bin"

	.align 2
DirectSoundWaveData_VIBE_76A::
	.incbin "sound/direct_sound_samples/gswavetable/VIBE_76A.bin"

	.align 2
DirectSoundWaveData_VIBE_88A::
	.incbin "sound/direct_sound_samples/gswavetable/VIBE_88A.bin"

	.align 2
DirectSoundWaveData_VIBE_A0A::
	.incbin "sound/direct_sound_samples/gswavetable/VIBE_A0A.bin"

	.align 2
DirectSoundWaveData_VIOLN68::
	.incbin "sound/direct_sound_samples/gswavetable/VIOLN68.bin"

	.align 2
DirectSoundWaveData_VIOLN70::
	.incbin "sound/direct_sound_samples/gswavetable/VIOLN70.bin"

	.align 2
DirectSoundWaveData_VIOLN76::
	.incbin "sound/direct_sound_samples/gswavetable/VIOLN76.bin"

	.align 2
DirectSoundWaveData_VIOLN80::
	.incbin "sound/direct_sound_samples/gswavetable/VIOLN80.bin"

	.align 2
DirectSoundWaveData_VIOLN86::
	.incbin "sound/direct_sound_samples/gswavetable/VIOLN86.bin"

	.align 2
DirectSoundWaveData_VIOLN95::
	.incbin "sound/direct_sound_samples/gswavetable/VIOLN95.bin"

	.align 2
DirectSoundWaveData_VIOLNA4::
	.incbin "sound/direct_sound_samples/gswavetable/VIOLNA4.bin"

	.align 2
DirectSoundWaveData_WCHIM60A::
	.incbin "sound/direct_sound_samples/gswavetable/WCHIM60A.bin"

	.align 2
DirectSoundWaveData_WIND_60::
	.incbin "sound/direct_sound_samples/gswavetable/WIND_60.bin"

	.align 2
DirectSoundWaveData_WODBK60::
	.incbin "sound/direct_sound_samples/gswavetable/WODBK60.bin"

	.align 2
DirectSoundWaveData_WRMPD72A::
	.incbin "sound/direct_sound_samples/gswavetable/WRMPD72A.bin"

	.align 2
DirectSoundWaveData_XYLO_72::
	.incbin "sound/direct_sound_samples/gswavetable/XYLO_72.bin"

	.align 2
DirectSoundWaveData_XYLO_93::
	.incbin "sound/direct_sound_samples/gswavetable/XYLO_93.bin"

