	.align 2
voicegroup191::
    voice_keysplit voicegroup192, KeySplitTable6
    voice_keysplit voicegroup192, KeySplitTable7
    voice_keysplit voicegroup192, KeySplitTable8
    voice_keysplit voicegroup193, KeySplitTable9
    voice_keysplit voicegroup194, KeySplitTable10
    voice_keysplit voicegroup195, KeySplitTable11
    voice_keysplit voicegroup196, KeySplitTable12
    voice_keysplit voicegroup197, KeySplitTable13
    voice_keysplit voicegroup198, KeySplitTable14    
    voice_keysplit voicegroup199, KeySplitTable15
    voice_keysplit voicegroup200, KeySplitTable16
    voice_keysplit voicegroup201, KeySplitTable17
    voice_keysplit voicegroup202, KeySplitTable18
    voice_keysplit voicegroup203, KeySplitTable19
    voice_keysplit voicegroup204, KeySplitTable20
    voice_keysplit voicegroup205, KeySplitTable21
    voice_keysplit voicegroup206, KeySplitTable22
    voice_keysplit voicegroup207, KeySplitTable23
    voice_keysplit voicegroup208, KeySplitTable24
    voice_keysplit voicegroup209, KeySplitTable25
    voice_keysplit voicegroup210, KeySplitTable26
    voice_keysplit voicegroup211, KeySplitTable27
    voice_keysplit voicegroup212, KeySplitTable28
    voice_keysplit voicegroup213, KeySplitTable29
    voice_keysplit voicegroup214, KeySplitTable30
    voice_keysplit voicegroup215, KeySplitTable31
    voice_keysplit voicegroup216, KeySplitTable32
    voice_keysplit voicegroup217, KeySplitTable33
    voice_keysplit voicegroup218, KeySplitTable34
    voice_keysplit voicegroup219, KeySplitTable35
    voice_keysplit voicegroup220, KeySplitTable36
    voice_keysplit voicegroup221, KeySplitTable37
    voice_keysplit voicegroup222, KeySplitTable38
    voice_keysplit voicegroup223, KeySplitTable39
    voice_keysplit voicegroup224, KeySplitTable40
    voice_keysplit voicegroup225, KeySplitTable41
    voice_keysplit voicegroup226, KeySplitTable42
    voice_keysplit voicegroup227, KeySplitTable43
    voice_keysplit voicegroup228, KeySplitTable44
    voice_keysplit voicegroup229, KeySplitTable45
    voice_keysplit voicegroup230, KeySplitTable46
    voice_keysplit voicegroup230, KeySplitTable47
    voice_keysplit voicegroup231, KeySplitTable48
    voice_keysplit voicegroup232, KeySplitTable49
    voice_keysplit voicegroup233, KeySplitTable50
    voice_keysplit voicegroup234, KeySplitTable51
    voice_keysplit voicegroup235, KeySplitTable52
    voice_keysplit voicegroup236, KeySplitTable53
    voice_keysplit voicegroup237, KeySplitTable54
    voice_keysplit voicegroup237, KeySplitTable54
    voice_keysplit voicegroup238, KeySplitTable55
    voice_keysplit voicegroup238, KeySplitTable56
    voice_keysplit voicegroup239, KeySplitTable57
    voice_keysplit voicegroup240, KeySplitTable58
    voice_keysplit voicegroup241, KeySplitTable59
    voice_directsound 60, 0, DirectSoundWaveData_O_HIT68, 255, 0, 255, 127
    voice_keysplit voicegroup242, KeySplitTable60
    voice_keysplit voicegroup243, KeySplitTable61
    voice_keysplit voicegroup244, KeySplitTable62
    voice_keysplit voicegroup245, KeySplitTable63
    voice_keysplit voicegroup246, KeySplitTable64
    voice_keysplit voicegroup247, KeySplitTable65
    voice_keysplit voicegroup248, KeySplitTable66
    voice_keysplit voicegroup249, KeySplitTable67
    voice_keysplit voicegroup250, KeySplitTable68
    voice_keysplit voicegroup251, KeySplitTable69
    voice_keysplit voicegroup252, KeySplitTable70
    voice_keysplit voicegroup253, KeySplitTable71
    voice_keysplit voicegroup254, KeySplitTable72
    voice_keysplit voicegroup255, KeySplitTable73
    voice_keysplit voicegroup256, KeySplitTable74
    voice_keysplit voicegroup257, KeySplitTable75
    voice_keysplit voicegroup258, KeySplitTable76
    voice_keysplit voicegroup259, KeySplitTable77
    voice_keysplit voicegroup260, KeySplitTable78
    voice_keysplit voicegroup261, KeySplitTable79
    voice_keysplit voicegroup262, KeySplitTable80
    voice_keysplit voicegroup263, KeySplitTable81
    voice_keysplit voicegroup264, KeySplitTable82
    voice_keysplit voicegroup265, KeySplitTable83
    voice_keysplit voicegroup266, KeySplitTable84
    voice_keysplit voicegroup267, KeySplitTable85
    voice_keysplit voicegroup268, KeySplitTable86
    voice_keysplit voicegroup269, KeySplitTable87
    voice_keysplit voicegroup270, KeySplitTable88
    voice_keysplit voicegroup271, KeySplitTable89
    voice_keysplit voicegroup272, KeySplitTable90
    voice_keysplit voicegroup273, KeySplitTable91
    voice_keysplit voicegroup274, KeySplitTable92
    voice_keysplit voicegroup275, KeySplitTable93
    voice_keysplit voicegroup276, KeySplitTable94
    voice_keysplit voicegroup277, KeySplitTable95
    voice_keysplit voicegroup278, KeySplitTable96
    voice_keysplit voicegroup279, KeySplitTable97
    voice_keysplit voicegroup280, KeySplitTable98
    voice_keysplit voicegroup281, KeySplitTable99
    voice_keysplit voicegroup282, KeySplitTable100
    voice_keysplit voicegroup283, KeySplitTable101
    voice_keysplit voicegroup284, KeySplitTable102
    voice_keysplit voicegroup285, KeySplitTable103
    voice_keysplit voicegroup286, KeySplitTable104
    voice_directsound 60, 0, DirectSoundWaveData_GOBLN84A, 255, 0, 255, 127
    voice_keysplit voicegroup287, KeySplitTable105
    voice_keysplit voicegroup288, KeySplitTable106
    voice_keysplit voicegroup289, KeySplitTable107
    voice_keysplit voicegroup290, KeySplitTable110
    voice_keysplit voicegroup291, KeySplitTable108
    voice_keysplit voicegroup292, KeySplitTable109
    voice_keysplit voicegroup293, KeySplitTable111
    voice_keysplit voicegroup294, KeySplitTable112
    @110
    @111
    @112
    @113
    @114
    @115
    @116
    @117
    @118
    @119
    @120
    @121
    @122
    @123
    @124
    @125
    @126
    @127
