	.align 1
gMetatiles_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_4g_tileset_exterior::
	.incbin "data/tilesets/primary/4g_tileset_exterior/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_exterior::
	.incbin "data/tilesets/primary/4g_tileset_exterior/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_outdoor_town::
	.incbin "data/tilesets/secondary/4g_tileset_outdoor_town/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_outdoor_town::
	.incbin "data/tilesets/secondary/4g_tileset_outdoor_town/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_outdoor_town2::
	.incbin "data/tilesets/secondary/4g_tileset_outdoor_town2/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_outdoor_town2::
	.incbin "data/tilesets/secondary/4g_tileset_outdoor_town2/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_outdoor_city::
	.incbin "data/tilesets/secondary/4g_tileset_outdoor_city/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_outdoor_city::
	.incbin "data/tilesets/secondary/4g_tileset_outdoor_city/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_outdoor_forest_house::
	.incbin "data/tilesets/secondary/4g_tileset_outdoor_forest_house/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_outdoor_forest_house::
	.incbin "data/tilesets/secondary/4g_tileset_outdoor_forest_house/metatile_attributes.bin"

	.align 1
gMetatiles_4g_tileset_Burned_Tower::
	.incbin "data/tilesets/secondary/4g_tileset_burned_tower/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_Burned_Tower::
	.incbin "data/tilesets/secondary/4g_tileset_burned_tower/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_indoor::
	.incbin "data/tilesets/primary/4g_tileset_indoor/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_indoor::
	.incbin "data/tilesets/primary/4g_tileset_indoor/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_bedroom::
	.incbin "data/tilesets/secondary/4g_tileset_bedroom/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_bedroom::
	.incbin "data/tilesets/secondary/4g_tileset_bedroom/metatile_attributes.bin"

	.align 1
gMetatiles_4g_tileset_lab::
	.incbin "data/tilesets/secondary/4g_tileset_lab/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_lab::
	.incbin "data/tilesets/secondary/4g_tileset_lab/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_pokecenter::
	.incbin "data/tilesets/secondary/4g_tileset_pokecenter/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_pokecenter::
	.incbin "data/tilesets/secondary/4g_tileset_pokecenter/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_cave::
	.incbin "data/tilesets/secondary/4g_tileset_cave/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_cave::
	.incbin "data/tilesets/secondary/4g_tileset_cave/metatile_attributes.bin"

	.align 1
gMetatiles_4g_tileset_mart::
	.incbin "data/tilesets/secondary/4g_tileset_mart/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_mart::
	.incbin "data/tilesets/secondary/4g_tileset_mart/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_indoor1::
	.incbin "data/tilesets/secondary/4g_tileset_indoor1/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_indoor1::
	.incbin "data/tilesets/secondary/4g_tileset_indoor1/metatile_attributes.bin"

	.align 1
gMetatiles_4g_tileset_flyarena::
	.incbin "data/tilesets/secondary/4g_tileset_flyarena/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_flyarena::
	.incbin "data/tilesets/secondary/4g_tileset_flyarena/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_woodtower::
	.incbin "data/tilesets/secondary/4g_tileset_woodtower/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_woodtower::
	.incbin "data/tilesets/secondary/4g_tileset_woodtower/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_underground::
	.incbin "data/tilesets/secondary/4g_tileset_underground/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_underground::
	.incbin "data/tilesets/secondary/4g_tileset_underground/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_indoor2::
	.incbin "data/tilesets/secondary/4g_tileset_indoor2/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_indoor2::
	.incbin "data/tilesets/secondary/4g_tileset_indoor2/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_indoor3::
	.incbin "data/tilesets/secondary/4g_tileset_indoor3/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_indoor3::
	.incbin "data/tilesets/secondary/4g_tileset_indoor3/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_ruins::
	.incbin "data/tilesets/secondary/4g_tileset_ruins/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_ruins::
	.incbin "data/tilesets/secondary/4g_tileset_ruins/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_park::
	.incbin "data/tilesets/secondary/4g_tileset_park/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_park::
	.incbin "data/tilesets/secondary/4g_tileset_park/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_dojo::
	.incbin "data/tilesets/secondary/4g_tileset_dojo/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_dojo::
	.incbin "data/tilesets/secondary/4g_tileset_dojo/metatile_attributes.bin"


	.align 1
gMetatiles_4g_tileset_flower_bike_store::
	.incbin "data/tilesets/secondary/4g_tileset_flower_bike_store/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_flower_bike_store::
	.incbin "data/tilesets/secondary/4g_tileset_flower_bike_store/metatile_attributes.bin"
	.align 1
gMetatiles_4g_tileset_subsoil::
	.incbin "data/tilesets/secondary/4g_tileset_subsoil/metatiles.bin"

	.align 1
gMetatileAttributes_4g_tileset_subsoil::
	.incbin "data/tilesets/secondary/4g_tileset_subsoil/metatile_attributes.bin"
